## Utility functions

In [24]:
import os
import numpy as np
import pandas as pd
import time
from scipy import stats
import scipy
from statsmodels.regression.linear_model import yule_walker
import multiprocessing
from statsmodels.tsa.ar_model import AR

import warnings
warnings.filterwarnings('ignore')

#### gibbs sampler with parallel computing, diagnosis, etc.
# N is the number of iterations
# R is the indicator matrix of observations, dim(R)=(n,m)
# Y is the ratings (binary), dim(Y)=(n,m)
# W is the user feature matrix, dim(W)=(n,J)
# X is the item feature matrix, dim(X)=(m,K)
# Z is the initialized indicators
# U is the initialized noise matrix, dim(U)=(n,L)
# V is the initialized noise matrix, dim(V)=(m,L)
# L is the dimension of U_i and V_j
# alpha_y, beta_y, sigma_u2, sigma_v2 are initial values from prior
# alp_u, beta_u, alp_v, beta_v, sig_y2 are prior parameters (we choose sig_y2 large for a flat prior)
# N_tot is the total number of iterations
# N_sing is the number of iterations for each check
# n_chain is the number of markov chains
def full_gibbs(N_tot, N_sing, n_chain, R, Y, W, X, Z, L, alp_u, beta_u, alp_v, beta_v, sig_y2, a_r, b_r):
    pool = multiprocessing.Pool(processes=n_chain)
    
    # initiate
    args = []
    for i in range(n_chain):
        init = initial_gibbs(Y,W,X,Z,R,L,sig_y2, alp_u, beta_u, alp_v, beta_v, a_r, b_r)
        new_arg = list((N_sing,R,Y,W,X) + init + (alp_u, beta_u, alp_v, beta_v, sig_y2))
        args.append(new_arg)
    results = pool.map(base_gibbs_wrapper, args)

#### initialize samples for a gibbs sampler chain
def initial_gibbs(Y,W,X,Z,R,L, sig_y2, alp_u, beta_u, alp_v, beta_v, a_r, b_r):
    n, m = R.shape
    J = W.shape[1]
    K = X.shape[1]
    
    # sample from prior to start ~ start from estimator
    alpha_y = np.random.normal(0, np.sqrt(sig_y2), size = (1,K)) # alpha_y ~ N(0,sigma_y^2 I_K)
    beta_y = np.random.normal(0, np.sqrt(sig_y2), size = (1,J)) # beta_y ~ N(0,sigma_y^2 I_J)
    sigma_u2 = stats.invgamma.rvs(a= alp_u, scale = beta_u, size=1) # sigma_u^2 ~ IG(alp_u, beta_u)
    sigma_v2 = stats.invgamma.rvs(a= alp_v, scale = beta_v, size=1) # sigma_v^2 ~ IG(alp_v, beta_v)
    p_r = np.random.beta(a_r, b_r, size=1)
   
    
    # sample initial from kinds of posterior / expectation
    U = np.random.normal(0,1, (n, L)) # sample iid N(0,1)
    V = np.random.normal(0,1, (m, L)) # sample iid N(0,1)
    Z = np.zeros((n,m))
    for i in range(n):
        for j in range(m):
            if R[i,j] == 1 and Y[i,j] == 0:
                Z[i,j] = -np.sqrt(2/np.pi)
            elif R[i,j] ==1 and Y[i,j] == 1:
                Z[i,j] = np.sqrt(2/np.pi)
    
    # sample posterior in gibbs sampler
    a_p = a_r + sum(sum(R))
    b_p = b_r + sum(sum(1-R))
    p_e = np.random.beta(a_p, b_p, size=1)
    
    return( (Z, U, V, alpha_y, beta_y, sigma_u2, sigma_v2) )
    
def base_gibbs_wrapper(args):
    return base_gibbs(*args)

#### the basic gibbs sampler
# N is the number of iterations
# R is the indicator matrix of observations, dim(R)=(n,m)
# Y is the ratings (binary), dim(Y)=(n,m)
# W is the user feature matrix, dim(W)=(n,J)
# X is the item feature matrix, dim(X)=(m,K)
# Z is the initialized indicators
# U is the initialized noise matrix, dim(U)=(n,L)
# V is the initialized noise matrix, dim(V)=(m,L)
# L is the dimension of U_i and V_j
# alpha_y, beta_y, sigma_u2, sigma_v2 are initial values from prior
# alp_u, beta_u, alp_v, beta_v, sig_y2 are prior parameters (we choose sig_y2 large for a flat prior)
def base_gibbs(N, R, Y, W, X, Z, U, V, alpha_y, beta_y, sigma_u2, sigma_v2, alp_u, beta_u, alp_v, beta_v, sig_y2):
    n, m = R.shape
    J = W.shape[1]
    K = X.shape[1]
    L = U.shape[1]
    
    SIG_U2 = []
    SIG_V2 = []
    ALP_Y = []
    BETA_Y = []
    UU = []
    VV = []
    ZZ = []
    TIMES = []
    LOG_LIKES = []
    
    OBi = []
    for i in range(n):
        observed = [j for j in range(m) if R[i,j]==1.0]
        OBi.append(observed)
    OBj = []
    for j in range(m):
        observed = [i for i in range(n) if R[i,j]==1.0]
        OBj.append(observed)
    
    start_time = time.time()
    
    for nn in range(N):
        if nn%100 == 0:
            now_time = time.time()
            TIMES.append(now_time - start_time)
            start_time = time.time()
        
        #print(nn)
        # sample sigma_u2 and sigma_v2
        sigma_u2 = stats.invgamma.rvs(a= alp_u + n*L/2, scale = beta_u + sum(sum(U*U))/2, size=1)
        sigma_v2 = stats.invgamma.rvs(a= alp_v + m*L/2, scale = beta_v + sum(sum(V*V))/2, size=1)
        SIG_U2.append(sigma_u2[0])
        SIG_V2.append(sigma_v2[0])
        
        # sample alpha_y and beta_y
        sig_alp = np.eye(K)/sig_y2
        sum_r = sum(R)
        for j in range(m):
            sig_alp = sig_alp + sum_r[j] * np.matmul(np.matrix(X[j,]).transpose(), np.matrix(X[j,]))
        L_alp = np.linalg.cholesky(sig_alp)
        Linv_alp = scipy.linalg.solve_triangular(L_alp, np.eye(K), lower=True)
        sig_alp = np.matmul(Linv_alp.transpose(), Linv_alp) #choleskey decomp
        
        sig_beta = np.eye(J)/sig_y2
        sum_rt = sum(R.transpose())
        for i in range(n):
            sig_beta = sig_beta + sum_rt[i] * np.matmul(np.matrix(W[i,]).transpose(), np.matrix(W[i,]))
        #sig_beta = np.linalg.inv(sig_beta)
        L_beta = np.linalg.cholesky(sig_beta)
        Linv_beta = scipy.linalg.solve_triangular(L_beta, np.eye(J), lower=True)
        sig_beta = np.matmul(Linv_beta.transpose(), Linv_beta)
        
        mu_alp = np.matrix(np.zeros(shape=(L,1))).reshape(-1)
        sum_rx = sum(np.array(R) * np.array((Z - np.matmul(W, beta_y.transpose()) - np.matmul(U,V.transpose()))))#save U'V
        for j in range(m):
            mu_alp = mu_alp + sum_rx[j] * X[j,]
        mu_alp = np.matmul(sig_alp, mu_alp.reshape((L,1)))
        
        mu_beta = np.matrix(np.zeros(shape=(L,1))).reshape(-1)
        sum_rw = sum(np.array(R.transpose()) * np.array(Z.transpose() - np.matmul(X, alpha_y.transpose()) - np.matmul(V,U.transpose())))
        for i in range(n):
            mu_beta = mu_beta + sum_rw[i] * W[i,]
        mu_beta = np.matmul(sig_beta, mu_beta.reshape((L,1)))
        
        #print(mu_alp,sig_alp)
        #alpha_y = np.random.multivariate_normal(mean = np.asarray(mu_alp).reshape(-1), cov=sig_alp, size=1)
        stand_alp = np.random.normal(size=K)
        alpha_y = mu_alp.reshape(-1) + np.matmul(Linv_alp.transpose(),stand_alp.reshape((K,1))).reshape(-1)
        #beta_y = np.random.multivariate_normal(mean = np.asarray(mu_beta).reshape(-1), cov=sig_beta, size=1)
        stand_beta = np.random.normal(size=J)
        beta_y = mu_beta.reshape(-1) + np.matmul(Linv_beta.transpose(),stand_beta.reshape((J,1))).reshape(-1)
        ALP_Y.append(alpha_y)
        BETA_Y.append(beta_y)
        
        # sample U_i and V_j
        for i in range(n):
            sig_ui = np.eye(L) / sigma_u2
            mu_ui = np.matrix(np.zeros(shape=(L,1))).reshape(-1)
            for j in OBi[i]:
                sig_ui = sig_ui + R[i,j] * np.matmul(np.matrix(V[j,]).transpose(), np.matrix(V[j,]))
                mu_ui = mu_ui + R[i,j] * (Z[i,j] - sum(sum(W[i,]*np.array(beta_y))) - sum(sum(X[j,]*np.array(alpha_y)))) * V[j,]
            #sig_ui = np.linalg.inv(sig_ui)
            L_ui = np.linalg.cholesky(sig_ui)
            Linv_ui = scipy.linalg.solve_triangular(L_ui, np.eye(L), lower=True)
            sig_ui = np.matmul(Linv_ui.transpose(), Linv_ui)
            mu_ui = np.matmul(sig_ui, mu_ui.reshape(L,1))
            #U[i,] = np.random.multivariate_normal(mean = np.asarray(mu_ui).reshape(-1), cov=sig_ui, size=1)
            stand_ui = np.random.normal(size=L)
            U[i,] = mu_ui.reshape(-1) + np.matmul(Linv_ui.transpose(),stand_ui.reshape((L,1))).reshape(-1)
        
        for j in range(m):
            sig_vj = np.eye(L) / sigma_v2
            mu_vj = np.matrix(np.zeros(shape=(L,1))).reshape(-1)
            for i in OBj[j]:
                sig_vj = sig_vj + R[i,j] * np.matmul(np.matrix(U[i,]).transpose(), np.matrix(U[i,]))
                mu_vj = mu_vj + R[i,j] * (Z[i,j] - sum(sum(W[i,]*np.array(beta_y))) - sum(sum(X[j,]*np.array(alpha_y)))) * U[i,]
            #sig_vj = np.linalg.inv(sig_vj)
            L_vj = np.linalg.cholesky(sig_vj)
            Linv_vj = scipy.linalg.solve_triangular(L_vj, np.eye(L), lower=True)
            sig_vj = np.matmul(Linv_vj.transpose(), Linv_vj)
            mu_vj = np.matmul(sig_vj, mu_vj.reshape(L,1))
            #V[j,] = np.random.multivariate_normal(mean = np.asarray(mu_vj).reshape(-1), cov=sig_vj, size=1)
            stand_vj = np.random.normal(size=K)
            V[j,] = mu_vj.reshape(-1) + np.matmul(Linv_vj.transpose(),stand_vj.reshape((L,1))).reshape(-1)
        
        UU.append(U)
        VV.append(V)
            
        # sample Z_ij
        zmean = np.matmul(W, beta_y.reshape((J,1))) + np.matmul(X, alpha_y.reshape((K,1))).transpose() + np.matmul(U, V.transpose())
        for i in range(n):
            for j in OBi[i]:
                if Y[i,j] == 1:
                    if stats.norm.cdf(zmean[i,j]) > 0.01:
                        Z[i,j] = stats.truncnorm.rvs(-zmean[i,j], np.inf, loc=zmean[i,j],scale=1,size=1)
                else:
                    if stats.norm.cdf(zmean[i,j]) <0.99:
                        Z[i,j] = stats.truncnorm.rvs(-np.inf, -zmean[i,j], loc=zmean[i,j],scale=1,size=1)
        ZZ.append(Z)
        
        # compute likelihood
        log_like = log_likelihood(Y,R,X,W, Z,U,V,sigma_u2,sigma_v2,alpha_y, beta_y, sig_y2, alp_u, alp_v, beta_u, beta_v)
        LOG_LIKES.append(log_like)
        
        print(alpha_y)
        print(beta_y)

    return SIG_U2, SIG_V2, ALP_Y, BETA_Y, UU, VV, ZZ, LOG_LIKES, TIMES

    
def spec(x, order=2):
    beta, sigma = yule_walker(x,order)
    return sigma**2 / (1. - np.sum(beta))**2

def log_likelihood(Y,R,X,W, Z,U,V,sigma_u2,sigma_v2,alpha_y, beta_y, sig_y2, alp_u, alp_v, beta_u, beta_v):
    n, m = R.shape
    J = W.shape[1]
    K = X.shape[1]
    L = U.shape[1]
    
    ll = 0
    for i in range(n):
        for j in range(m):
            if R[i,j] == 1:
                ll -= 0.5 * (Z[i,j] - sum(sum(W[i,]*np.array(beta_y))) - sum(sum(X[j,]*np.array(alpha_y))) - sum(U[i,]*V[j,]))**2
                ll -= 0.5 * sum(sum(np.array(beta_y)**2))/sig_y2 + 0.5 * sum(sum(np.array(alpha_y)**2))/sig_y2
    ll -= np.log(sigma_u2) * 0.5 * (n*L+2*alp_u+2) + np.log(sigma_v2) * (m*L+2*alp_v+2)*0.5
    ll -= 0.5 * (sum(sum(U**2)) + beta_u) / sigma_u2 + 0.5 * ( sum(sum(V**2)) + beta_v ) / sigma_v2
    
    return(ll[0])

# df is a dataframe of all sampled parameters
def EffectiveSize(df):
    nn, mm = df.shape
    df.columns = ["0"]*mm
    v0 = []
    ESS = []
    for jj in range(mm):
        xx = df.iloc[:,jj]
        xx_mod = AR(xx)
        xx_res = xx_mod.fit(maxlag=100,ic='aic')
        v0.append(xx_res.sigma2/(1.0-sum(xx_res.params))**2)
    for jj in range(mm):
        xx = df.iloc[:,jj]
        ess = xx.std()**2 / v0[jj] * nn
        ESS.append(ess)
    return(ESS)
    
    
    

## Simulations

In [25]:
import os
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.regression.linear_model import yule_walker
import multiprocessing

#dir_name = "/home/yingjin/gibbs/rec_engine_stream/simulations/gibbs/workflow"
#os.chdir(dir_name)
from gibbs_funcs import base_gibbs
from gibbs_funcs import base_gibbs_wrapper
from gibbs_funcs import initial_gibbs
from gibbs_funcs import EffectiveSize

Set Parameters for priors

In [26]:
a_r, b_r = 1, 1 # R_{ij} ~ Bern(p), p ~ Beta(a_r, b_r)
alp_u, beta_u = 1, 1 # U_i ~ N(0, sig_u^2), sig_u^2 ~ IG(alp_u, beta_u)
alp_v, beta_v = 1, 1 # V-j ~ N(0, sig_v^2), sig_v^2 ~ IG(alp_v, beta_v)
sig_y2 = 10 # alpha_y ~ N(0,sigma_y^2 I_K), beta_y ~ N(0,sigma_y^2 I_J)

Set dimensions of data

In [27]:
mnid=1
ns = [100, 1000, 5000]
ms = [20, 200, 2000]
n = ns[mnid]
m = ms[mnid]

In [28]:
random_dim=2
J = random_dim # dimension of beta_y and W_i
K = random_dim # dimension of alpha_y and X_j
L = random_dim # dimension of U_i and V_j
coef_scale=5.0

generate simulation data, where beta0, alpha0 are true parameters

In [29]:
X = np.random.normal(0,1, (m,K))
W = np.random.normal(0,1, (n,J))
beta0 = (2*np.random.binomial(1,0.5,J).reshape((J,1)) -1)* coef_scale #np.random.normal(0,1, (J,1)) # true beta0 ~ uniform, larger value
alpha0 = (2*np.random.binomial(1,0.5,J).reshape((J,1)) -1)* coef_scale #np.random.normal(0,1, (K,1)) # true alpha0
U = np.random.normal(0,1, (n, L)) # truth: sigma_u = 1
V = np.random.normal(0,1, (m, L)) # truth: sigma_v = 1
Zmeans = np.matmul(W, beta0) + np.matmul(X, alpha0).transpose() + np.matmul(U, V.transpose())
Z = Zmeans + np.random.normal(0,1, (n,m)) # var of Zmeans should be large
R = np.random.binomial(1, 0.01, (n,m)) # truth: p_r = 0.1
Y = 1.0 * (Z>0)
for i in range(n):
    for j in range(m):
        if R[i,j]==0:
            Y[i,j] = float("nan")

snr = Zmeans[R>0].std()**2/ Z[R>0].std()**2

In [30]:
snr

0.9853728248444464

In [31]:
N_tot = 50000 # the limit of all iterations
N_sing = 500 # num of iterations before each check
n_chain = 3

## Burn-in Process

In [ ]:
# set parallel computing
pool = multiprocessing.Pool(processes=n_chain)


# initiate
args = []
for i in range(n_chain):
    # initial_gibbs returns tuple (Z,U,V,alpha_y,beta_y,sigma_u2,sigma_v2)
    init = initial_gibbs(Y,W,X,Z,R,L,sig_y2, alp_u, beta_u, alp_v, beta_v, a_r, b_r)
    new_arg = list((N_sing,R,Y,W,X) + init + (alp_u, beta_u, alp_v, beta_v, sig_y2))
    args.append(new_arg)

count = 0

# record results
all_alpy = [pd.DataFrame()] * n_chain
all_betay = [pd.DataFrame()] * n_chain
all_sigu2 = [pd.DataFrame()] * n_chain
all_sigv2 = [pd.DataFrame()] * n_chain
all_paras = [pd.DataFrame()] * n_chain

#########################
# burnin
if_continue = True
while count < N_tot and if_continue:

    # run a batch of N_sing iterations
    results = pool.map(base_gibbs_wrapper, args)
    count += N_sing

    # process the results
    for i in range(n_chain):
        # subtract results for each chain
        tmp_res = results[i]
        tmp_alpy = tmp_res[2]
        tmp_betay = tmp_res[3]
        tmp_sigu2 = tmp_res[0]
        tmp_sigv2 = tmp_res[1]
        UU = tmp_res[4]
        VV = tmp_res[5]
        ZZ = tmp_res[6]

        # update args
        new_arg  = list((N_sing, R,Y,W,X, ZZ[-1], UU[-1], VV[-1],tmp_alpy[-1], tmp_betay[-1], 
                         tmp_sigu2[-1], tmp_sigv2[-1], alp_u, beta_u, alp_v, beta_v, sig_y2))
        args[i] = new_arg

        # concatenate results
        tmp_alpy_mat = np.matrix(np.zeros(shape=(N_sing,J)))
        tmp_betay_mat = np.matrix(np.zeros(shape=(N_sing,J)))

        for jj in range(N_sing):
            tmp_alpy_mat[jj,] = tmp_alpy[jj]
            tmp_betay_mat[jj,] = tmp_betay[jj]

        all_alpy[i] = pd.concat([all_alpy[i], pd.DataFrame(tmp_alpy_mat)]) 
        all_betay[i] = pd.concat([all_betay[i], pd.DataFrame(tmp_betay_mat)]) 
        all_sigu2[i] = pd.concat([all_sigu2[i], pd.DataFrame(tmp_sigu2)]) 
        all_sigv2[i] = pd.concat([all_sigv2[i], pd.DataFrame(tmp_sigu2)]) 

        all_paras[i] = pd.concat([all_paras[i],
                                  pd.concat([pd.DataFrame(tmp_alpy_mat), 
                                             pd.DataFrame(tmp_betay_mat), 
                                             pd.DataFrame(tmp_sigu2), 
                                             pd.DataFrame(tmp_sigv2)],axis=1)])


    # diagnostic for burnin
    # Gelman-Rubin test
    if_pass = True
    n_paras = (all_paras[0]).shape[1]
    NN = int(all_paras[0].shape[0]/2)

    hatrs = np.array([0.0]*n_paras)
    for jj in range(n_paras):
        means = []
        stds = []
        for ii in range(n_chain):
            mean = all_paras[ii].iloc[NN:NN*2,jj].mean()
            sd = all_paras[ii].iloc[NN:NN*2,jj].std()
            means.append(mean)
            stds.append(sd)
        means = np.array(means)
        stds = np.array(stds)
        ww = np.mean(stds**2)
        bb = np.std(means) **2 * NN

        hatvar = (1-1/NN)*ww + bb/NN
        hatr = np.sqrt(hatvar/ww)
        hatrs[jj] = hatr

    if_pass = sum((1.0<=hatrs)&(hatrs<=1.1)) == n_paras
    if if_pass:
        if_continue = False

0
[[ 0.32605869 -0.39142837]]
[[0.08614119 0.28522123]]
0
0
[[ 0.412287   -0.47147704]]
[[ 0.35064057 -0.40623983]]
[[0.21971395 0.34505564]]
[[0.27663687 0.3011075 ]]
1
[[ 0.48765707 -0.55234542]]
[[0.3184873  0.48573055]]
1
[[ 0.50495816 -0.57069893]]
1
[[ 0.54695234 -0.61541201]]
[[0.43750104 0.5002193 ]]
[[0.40497584 0.52840887]]
2
[[ 0.608288   -0.62959339]]
[[0.5156076  0.59154221]]
2
[[ 0.62699706 -0.64729676]]
[[0.5939301  0.61020374]]
2
[[ 0.6584397  -0.67609895]]
[[0.57738784 0.63294554]]
3
[[ 0.7097134  -0.65423728]]
[[0.61763267 0.68792446]]
3
[[ 0.72806579 -0.67426408]]
[[0.67390255 0.70493808]]
3
[[ 0.75149752 -0.69659462]]
[[0.66493241 0.7228721 ]]
4
[[ 0.82647945 -0.72480613]]
[[0.75284805 0.80229364]]
4
[[ 0.8442558  -0.74382923]]
[[0.79568291 0.81930062]]
4
[[ 0.86237065 -0.76073771]]
[[0.79177393 0.83434064]]
5
[[ 0.87888806 -0.8147843 ]]
[[0.8191281  0.84290225]]
5
[[ 0.91129666 -0.84652303]]
5
[[0.85260882 0.87205628]]
[[ 0.89642266 -0.83296856]]
[[0.85348609 0.858

[[1.73292342 1.8391725 ]]
49
[[ 1.84599451 -1.74755029]]
[[1.76933396 1.84639856]]
48
[[ 1.89391688 -1.74567704]]
[[1.73321007 1.86209991]]
48
[[ 1.90052974 -1.75205132]]
[[1.73981306 1.86863683]]
50
[[ 1.84008509 -1.74565212]]
[[1.78290038 1.83683674]]
49
[[ 1.84781577 -1.7492919 ]]
49
[[1.7711319  1.84817779]]
[[ 1.8412827  -1.74302799]]
[[1.76464033 1.84173118]]
51
[[ 1.82884019 -1.79889567]]
[[1.73266683 1.86607154]]
50
[[ 1.84188408 -1.74736099]]
[[1.7846735  1.83858551]]
50
[[ 1.83542861 -1.74121115]]
[[1.7782737  1.83224801]]
51
52
[[ 1.8306088 -1.8005733]]
[[ 1.78458318 -1.85313891]]
[[1.77397291 1.82791928]]
[[1.73441178 1.86779624]]
53
[[ 1.79235686 -1.82785041]]
[[1.77445836 1.85922362]]
51
[[ 1.8242584  -1.79452852]]
52
[[1.72811709 1.86154612]]
[[ 1.78631072 -1.85479884]]
[[1.775677   1.82962327]]
52
[[ 1.78009875 -1.84881616]]
[[1.76952198 1.82345539]]
53
[[ 1.79405236 -1.82948661]]
[[1.77613548 1.86089548]]
54
[[ 1.81324185 -1.83946003]]
[[1.7776333  1.85930427]]
55
[[ 1

[[1.93693578 2.12022271]]
96
[[ 2.12493545 -2.10882136]]
[[1.93334733 2.1166538 ]]
96
[[ 2.12749204 -2.11137625]]
[[1.93594761 2.1192408 ]]
97
[[ 2.15100287 -2.07603159]]
[[1.92350453 2.13688088]]
97
[[ 2.14751275 -2.07255543]]
[[1.9199725  2.13334654]]
97
[[ 2.15004274 -2.07507516]]
[[1.92253183 2.13590847]]
98
[[ 2.14254372 -2.13898667]]
[[1.97065497 2.21390232]]
98
[[ 2.13908702 -2.13553716]]
[[1.96718712 2.21040587]]
99
[[ 2.21049246 -2.11347952]]
[[2.0415822  2.24423255]]
98
[[ 2.14159295 -2.13803748]]
[[1.96970001 2.21294035]]
100
[[ 2.25972978 -2.12091321]]
[[2.03053136 2.20979305]]
99
[[ 2.20708017 -2.11006395]]
[[2.0381732  2.24074937]]
99
[[ 2.2095541  -2.11253966]]
[[2.04064349 2.24327418]]
100
[[ 2.25635266 -2.11754844]]
[[2.02714566 2.2063428 ]]
101
[[ 2.26288    -2.12167549]]
[[2.0435011  2.22626424]]
100
[[ 2.25880123 -2.11998747]]
[[2.02959884 2.20884391]]
101
[[ 2.25951627 -2.11835845]]
[[2.04015341 2.22285969]]
102
[[ 2.20228651 -2.13673761]]
[[2.04701143 2.23532409]]

[[ 2.44598733 -2.46840179]]
[[2.50043335 2.56586895]]
143
[[ 2.21315871 -2.32819247]]
[[2.33377811 2.27054692]]
144
[[ 2.4561438  -2.50292161]]
[[2.44161958 2.5626448 ]]
144
[[ 2.45551958 -2.50231536]]
[[2.44099366 2.56202448]]
144
[[ 2.20337647 -2.34651436]]
[[2.29248608 2.27540472]]
145
[[ 2.42707206 -2.51900451]]
145
[[2.54436777 2.64236976]]
[[ 2.42645544 -2.51840203]]
[[2.5437456  2.64175387]]
145
[[ 2.22299912 -2.34306773]]
[[2.29387083 2.25934078]]
146
[[ 2.449902   -2.52125871]]
[[2.5308163  2.63770894]]
146
[[ 2.4492894  -2.52065863]]
[[2.53020062 2.6370986 ]]
146
[[ 2.25854468 -2.29132418]]
[[2.29741156 2.29434439]]
147
[[ 2.47072746 -2.52017948]]
[[2.55841921 2.61146302]]
147
[[ 2.47133588 -2.52077768]]
[[2.55902648 2.61206758]]
147
[[ 2.24031531 -2.27428243]]
[[2.36500621 2.35249282]]
148
[[ 2.49245335 -2.56707883]]
[[2.52621357 2.54078963]]
148
[[ 2.49305898 -2.56767343]]
[[2.52681696 2.54138624]]
148
[[ 2.31662983 -2.26595169]]
[[2.34594799 2.38368248]]
149
[[ 2.47827272 

[[2.63922839 2.6223703 ]]
191
[[ 2.61930672 -2.69073867]]
[[2.67813176 2.73857962]]
190
[[ 2.5753294  -2.65263789]]
[[2.67335984 2.71178881]]
191
[[ 2.59773115 -2.57405307]]
[[2.66758082 2.62410944]]
191
[[ 2.61973408 -2.69117095]]
[[2.67857312 2.73902357]]
192
[[ 2.58319156 -2.70336123]]
[[2.64800191 2.71723584]]
192
[[ 2.60244354 -2.61757476]]
[[2.64560216 2.65873349]]
192
[[ 2.58361656 -2.70378791]]
[[2.64844133 2.71767709]]
193
[[ 2.56796661 -2.72172187]]
[[2.66295316 2.69945138]]
193
[[ 2.5683895  -2.72214703]]
[[2.6633891  2.69988876]]
193
[[ 2.57179401 -2.56953939]]
[[2.66909493 2.7397082 ]]
194
[[ 2.53675801 -2.73631416]]
[[2.70880935 2.78542915]]
194
[[ 2.53633854 -2.73588914]]
[[2.70837603 2.78499731]]
195
[[ 2.60186487 -2.75276437]]
[[2.70631931 2.78694722]]
194
[[ 2.62106553 -2.59989274]]
[[2.70191614 2.77118801]]
195
[[ 2.60144829 -2.75234229]]
[[2.70588899 2.7865186 ]]
196
[[ 2.63416609 -2.71241823]]
[[2.70058621 2.74816618]]
195
[[ 2.57437175 -2.62010711]]
[[2.72338005 2

237
[[ 2.83302364 -2.85346669]]
[[2.84040949 2.91354555]]
237
[[ 2.75602712 -2.75254526]]
[[2.84415958 2.88954525]]
239
[[ 2.81710412 -2.80956047]]
[[2.76780121 2.92855501]]
238
[[ 2.8325183  -2.79053128]]
[[2.79267013 2.92681994]]
240
[[ 2.82818559 -2.81515415]]
[[2.78596929 2.90859881]]
238
[[ 2.71117968 -2.77462387]]
[[2.80287686 2.890507  ]]
241
[[ 2.83531977 -2.78180651]]
[[2.79928051 2.94928594]]
239
[[ 2.81741798 -2.80988298]]
[[2.76813143 2.92888553]]
242
239
[[ 2.85588679 -2.75459218]]
[[ 2.71196509 -2.75480592]]
[[2.77791955 2.88834833]]
[[2.81987739 2.9862278 ]]
240
[[ 2.82849917 -2.8154735 ]]
[[2.78629745 2.90892774]]
240
[[ 2.72648636 -2.80355584]]
[[2.74369476 2.86395161]]
243
[[ 2.81637409 -2.77806366]]
[[2.81351801 2.99229721]]
241
241
[[ 2.7500529  -2.81883908]]
[[2.74799351 2.92577736]]
[[ 2.83563211 -2.78212454]]
[[2.79960667 2.94961277]]
244
[[ 2.84728196 -2.76515111]]
[[2.81956939 3.0256347 ]]
242
[[ 2.85619818 -2.75490749]]
[[2.82020077 2.98655368]]
242
[[ 2.72990

[[3.00872983 3.18501686]]
282
[[ 2.91394169 -2.93912364]]
[[2.99913808 2.98957845]]
286
[[ 2.93020775 -3.03808611]]
[[3.00898549 3.18527771]]
287
[[ 2.94260761 -3.06550895]]
[[2.98692419 3.21158322]]
283
[[ 2.90114997 -2.97863198]]
287
[[3.00644724 2.99012897]]
[[ 2.94286152 -3.06576111]]
[[2.98717824 3.21184308]]
288
[[ 2.96592502 -3.08770388]]
[[3.00116058 3.22162646]]
284
[[ 2.91261929 -2.94879021]]
[[2.99901512 2.97406988]]
288
[[ 2.96617678 -3.08795502]]
[[3.00141364 3.22188586]]
289
[[ 2.96284027 -3.10405188]]
[[3.04259544 3.23111811]]
285
[[ 2.93320615 -2.9267837 ]]
[[2.96763594 3.05051825]]
290
[[ 2.97863041 -3.13346836]]
[[3.07691319 3.25664102]]
289
[[ 2.96309049 -3.10430176]]
[[3.04284752 3.23137683]]
286
[[ 2.93990775 -2.92601974]]
[[2.9680683  3.05291778]]
291
[[ 3.00802785 -3.10685004]]
[[3.15708843 3.25390944]]
290
[[ 2.97887865 -3.13371786]]
[[3.07716393 3.25689893]]
291
[[ 3.00827413 -3.10709924]]
[[3.15733804 3.25416682]]
287
292
[[ 2.93121937 -2.95414162]]
[[2.994590

330
[[ 2.92167279 -2.96232651]]
[[2.89292073 2.91969893]]
333
[[ 3.19135797 -3.33524537]]
[[3.10209663 3.41697286]]
331
[[ 2.92159578 -2.98547037]]
[[2.86901567 3.0014785 ]]
333
[[ 3.19114582 -3.33503202]]
[[3.10188709 3.41674775]]
332
[[ 2.94704596 -3.01537732]]
[[2.86952095 2.99828957]]
334
[[ 3.25035085 -3.30563898]]
[[3.06620705 3.36281759]]
334
[[ 3.25013943 -3.30542621]]
[[3.06599871 3.36259306]]
333
[[ 3.00292147 -3.0293686 ]]
[[2.92597177 2.98602394]]
335
[[ 3.21228245 -3.36761822]]
[[3.08452195 3.3903908 ]]
335
[[ 3.21207158 -3.36740589]]
[[3.08431451 3.39016718]]
334
336
[[ 2.94495081 -3.04271728]]
[[2.90947504 3.00715475]]
[[ 3.22022415 -3.34761852]]
[[3.10400548 3.42889328]]
335
[[ 2.93462459 -3.07495487]]
[[2.88744402 3.03915799]]
337
[[ 3.22455192 -3.31683331]]
[[3.09891351 3.4358014 ]]
336
[[ 3.22001403 -3.34740625]]
[[3.10379914 3.42867017]]
336
[[ 2.91692161 -3.06542718]]
[[2.9217909  3.03343961]]
338
[[ 3.22578952 -3.29827542]]
[[3.13068724 3.36773626]]
337
[[ 3.22434

[[3.34636431 3.57040591]]
378
[[ 3.25087677 -3.40989951]]
[[3.34832245 3.58875818]]
381
[[ 3.25364105 -3.40264374]]
[[3.35800134 3.54873628]]
379
[[ 3.23097039 -3.35122284]]
[[3.31614879 3.55942477]]
379
[[ 3.0048253  -3.06729888]]
[[3.07771947 3.06036154]]
382
[[ 3.28994972 -3.31511985]]
[[3.32285706 3.53496201]]
380
[[ 3.22802813 -3.42829426]]
380
[[ 3.03385145 -3.09009598]]
[[3.06776283 3.07478238]]
[[3.34617831 3.57020617]]
383
[[ 3.25299079 -3.34731449]]
[[3.32527873 3.5434664 ]]
381
[[ 3.25346034 -3.40245249]]
[[3.3578157  3.54853686]]
381
[[ 3.02498796 -3.08914755]]
[[3.07173786 3.10987086]]
384
[[ 3.26341208 -3.36082929]]
[[3.30728393 3.5131773 ]]
382
[[ 3.00991228 -3.0459827 ]]
[[3.04587866 3.13048351]]
382
[[ 3.28976952 -3.31492898]]
[[3.32267162 3.53476327]]
385
[[ 3.24864337 -3.42362102]]
[[3.31715128 3.49540097]]
383
[[ 3.05358572 -3.08085441]]
[[3.07882103 3.19404296]]
386
[[ 3.30135857 -3.44195435]]
[[3.32676249 3.55693767]]
384
383
[[ 3.25281103 -3.34712465]]
[[ 3.03632

427
[[ 3.44333897 -3.48621638]]
[[3.38551752 3.60052792]]
426
[[ 3.13976214 -3.07593736]]
[[3.15006786 3.22736424]]
427
[[ 3.19369089 -3.11911972]]
[[3.15569883 3.26344485]]
426
[[ 3.44758615 -3.48532847]]
[[3.36892743 3.6421614 ]]
428
[[ 3.46873831 -3.4185957 ]]
[[3.36473176 3.60448236]]
428
[[ 3.17979608 -3.09932431]]
[[3.14682563 3.23062435]]
427
[[ 3.44317205 -3.48604265]]
[[3.38535589 3.6003459 ]]
429
[[ 3.49172393 -3.43246952]]
[[3.34490548 3.56977849]]
429
[[ 3.19428619 -3.10915281]]
[[3.10691143 3.15791464]]
428
[[ 3.46857145 -3.41842235]]
[[3.36457001 3.60430098]]
430
[[ 3.44994106 -3.43761747]]
[[3.38078909 3.5630912 ]]
430
[[ 3.17527466 -3.13294027]]
[[3.09226378 3.18106748]]
429
[[ 3.49155678 -3.43229646]]
[[3.34474421 3.56959819]]
431
[[ 3.46515792 -3.43419522]]
[[3.39516159 3.55348443]]
431
[[ 3.19328189 -3.07378583]]
[[3.07692991 3.12850213]]
432
[[ 3.51807969 -3.43959851]]
[[3.39557226 3.57570069]]
430
[[ 3.4497728  -3.43744489]]
[[3.38062864 3.56291201]]
432
[[ 3.11780

[[2.90815074 2.93546656]]
472
[[ 3.47018585 -3.44844362]]
[[3.37802696 3.45667248]]
476
[[ 3.55344911 -3.46651934]]
[[3.44777703 3.4351462 ]]
473
[[ 3.02941373 -2.89228666]]
[[2.91093915 2.91835412]]
477
[[ 3.501693   -3.39762664]]
[[3.42653265 3.49019119]]
473
[[ 3.44635836 -3.43161201]]
[[3.44044951 3.44716976]]
474
[[ 3.0250339 -2.9121416]]
[[2.95226522 2.90364367]]
478
[[ 3.50223807 -3.37211914]]
[[3.44196064 3.54639798]]
474
[[ 3.50706473 -3.50379897]]
[[3.46815925 3.46258758]]
475
[[ 3.02365481 -2.90119543]]
[[2.93976897 2.98143923]]
479
[[ 3.49830637 -3.39794222]]
[[3.39773564 3.56858871]]
480
[[ 3.49334411 -3.44030264]]
[[3.38962292 3.54373629]]
476
[[ 3.03950516 -2.93034379]]
[[2.99047216 3.00973884]]
475
[[ 3.51076941 -3.52473156]]
[[3.43818654 3.46103736]]
477
[[ 3.01744325 -3.0112716 ]]
[[2.9588048  3.04727152]]
481
[[ 3.46859477 -3.37256749]]
[[3.37447896 3.48229297]]
476
[[ 3.55328672 -3.46636235]]
[[3.44761456 3.43498652]]
482
[[ 3.50138588 -3.41199392]]
[[3.34643748 3.4

[[3.55902787 3.61357002]]
21
[[ 2.9387018 -3.1318684]]
[[2.9287231  3.08519161]]
21
[[ 3.47600209 -3.42958141]]
[[3.44962493 3.47085788]]
22
[[ 3.41426008 -3.43139974]]
[[3.49670944 3.61532031]]
22
[[ 3.00142481 -3.09125474]]
[[2.93944161 3.11101695]]
22
[[ 3.46998713 -3.47822591]]
[[3.4522876  3.52111112]]
23
[[ 3.44745356 -3.45887221]]
[[3.46427991 3.61962207]]
23
[[ 3.03778101 -3.1257454 ]]
[[2.92695552 3.10384751]]
23
[[ 3.48244864 -3.4698883 ]]
[[3.42817279 3.51999165]]
24
[[ 3.41903516 -3.41510007]]
[[3.49382518 3.61383274]]
24
[[ 3.05897162 -3.03735931]]
[[2.9935401  3.11510744]]
24
[[ 3.49133551 -3.46600298]]
[[3.48702028 3.51875636]]
25
[[ 3.40795352 -3.41683684]]
[[3.46422666 3.65519104]]
25
[[ 3.01466013 -3.06705166]]
[[3.06704293 3.09224177]]
25
[[ 3.50426507 -3.46517452]]
[[3.49544047 3.52719701]]
26
[[ 3.41349378 -3.41076445]]
[[3.41566389 3.63848869]]
26
[[ 3.02835055 -3.1112543 ]]
[[3.08408167 3.16829432]]
26
[[ 3.52036669 -3.4385401 ]]
[[3.5305398  3.51155564]]
27
[[ 3

[[ 3.40702062 -3.50349822]]
[[3.49647577 3.6220394 ]]
[[3.46008039 3.58041546]]
69
[[ 3.12033276 -3.13149647]]
[[3.08538359 3.28389733]]
71
[[ 3.39210989 -3.46036514]]
[[3.45987788 3.56067252]]
69
[[ 3.51620885 -3.43125356]]
[[3.4633479  3.59327018]]
70
[[ 3.09672669 -3.17639897]]
[[3.1123238  3.31594671]]
72
[[ 3.36244297 -3.47116045]]
[[3.50034816 3.53357645]]
70
[[ 3.53551812 -3.44541944]]
[[3.50451135 3.59511125]]
71
[[ 3.11942036 -3.19594977]]
[[3.08761179 3.30751637]]
73
[[ 3.31954204 -3.51417776]]
[[3.47166478 3.55544813]]
71
[[ 3.51244313 -3.48927837]]
[[3.52662121 3.58104119]]
72
[[ 3.14935605 -3.16056327]]
[[3.08735006 3.21048083]]
74
[[ 3.28362591 -3.52030401]]
[[3.45162443 3.53013125]]
72
[[ 3.51608126 -3.47720343]]
[[3.51094778 3.59990535]]
73
[[ 3.19194371 -3.18765186]]
[[3.09691868 3.19848569]]
75
[[ 3.27837538 -3.50242387]]
[[3.44538251 3.51633984]]
73
[[ 3.48171125 -3.47110593]]
[[3.50018426 3.5997757 ]]
74
[[ 3.12742822 -3.18784389]]
[[3.10976849 3.16972528]]
76
[[ 3.

118
[[ 3.19503153 -3.31232575]]
[[3.21776051 3.42152319]]
116
[[ 3.15441114 -3.18037799]]
[[3.08125495 3.31958571]]
117
[[ 3.51843547 -3.46901578]]
[[3.45335567 3.65750085]]
119
[[ 3.17822971 -3.34938514]]
[[3.25561956 3.46182549]]
117
[[ 3.15397936 -3.22494482]]
[[3.0847677  3.32028026]]
118
[[ 3.53700786 -3.45883068]]
[[3.45961768 3.68741111]]
119
[[ 3.52139238 -3.45501199]]
[[3.48206641 3.68156549]]
118
[[ 3.20216425 -3.19206636]]
[[3.06850342 3.31372695]]
120
[[ 3.22154721 -3.32519385]]
[[3.22557825 3.47412875]]
120
[[ 3.53099039 -3.4433793 ]]
[[3.44138053 3.68543383]]
119
[[ 3.23731199 -3.15906272]]
[[3.11719897 3.30945925]]
121
[[ 3.5218629  -3.46119231]]
[[3.5102846  3.69960027]]
121
[[ 3.25413276 -3.37181197]]
[[3.2291328  3.48002399]]
120
[[ 3.24789023 -3.14696325]]
[[3.11201656 3.38235459]]
122
[[ 3.57957281 -3.46018752]]
[[3.51020194 3.68583913]]
122
[[ 3.23477985 -3.36492566]]
[[3.27220533 3.47537657]]
121
[[ 3.20301535 -3.16100994]]
[[3.08247424 3.35944224]]
123
[[ 3.63110

[[3.16231967 3.20255318]]
165
[[ 3.54410374 -3.42980608]]
[[3.81789042 3.72661932]]
166
[[ 3.37959165 -3.34534718]]
[[3.214058  3.2628875]]
162
[[ 3.09575369 -3.22351234]]
[[3.17746579 3.21600215]]
166
[[ 3.53446428 -3.44922933]]
[[3.85705382 3.79805027]]
167
[[ 3.37675225 -3.35035824]]
[[3.20643735 3.31587638]]
163
[[ 3.09742351 -3.24919725]]
[[3.13130531 3.22741333]]
167
[[ 3.49254134 -3.44931274]]
[[3.82912603 3.80061236]]
168
[[ 3.38402975 -3.34760313]]
[[3.28418539 3.32103056]]
164
[[ 3.09943599 -3.24291501]]
[[3.11697643 3.22174529]]
168
[[ 3.4764192  -3.42280863]]
[[3.81518036 3.79491437]]
169
[[ 3.44566824 -3.35674276]]
[[3.2993722  3.34112547]]
165
[[ 3.09119496 -3.18848174]]
[[3.07959391 3.23231541]]
169
[[ 3.51158669 -3.49231042]]
[[3.82404229 3.75952797]]
170
[[ 3.49875533 -3.32400921]]
[[3.28550082 3.32830676]]
166
[[ 3.10164468 -3.20198218]]
[[3.04351739 3.2065253 ]]
170
[[ 3.57036652 -3.51405473]]
[[3.85447231 3.78063181]]
171
[[ 3.45914468 -3.2879576 ]]
[[3.26159243 3.3

212
[[ 3.36281022 -3.41498739]]
[[3.11331202 3.33428439]]
209
[[ 2.9310467  -3.10403501]]
[[3.10613236 3.15355543]]
213
[[ 3.56204576 -3.67997166]]
[[3.63559002 3.59567547]]
213
[[ 3.30817215 -3.43451461]]
[[3.09215777 3.35446062]]
210
[[ 2.92316205 -3.03579721]]
[[3.09899041 3.10646449]]
214
[[ 3.61507211 -3.74771749]]
[[3.66652684 3.67316072]]
214
[[ 3.35580388 -3.4351526 ]]
[[3.13720338 3.37215473]]
211
[[ 2.95301365 -3.03860358]]
[[3.03727444 3.10080403]]
215
[[ 3.6667255  -3.70363942]]
[[3.64702625 3.71583342]]
215
[[ 3.3140485  -3.41206387]]
[[3.204132   3.35791396]]
212
[[ 2.96654253 -3.04261985]]
[[3.0113447  3.06119566]]
216
[[ 3.65185766 -3.67674928]]
[[3.64841236 3.71662495]]
216
[[ 3.26427161 -3.35693848]]
[[3.20662805 3.39225011]]
213
[[ 2.91099216 -3.01084069]]
[[3.0458387  3.03878266]]
217
[[ 3.6945839  -3.62344525]]
[[3.586625   3.75682393]]
217
[[ 3.25556875 -3.3131927 ]]
[[3.12001673 3.37862113]]
214
[[ 2.85706473 -2.98578931]]
[[3.05468875 3.07897516]]
218
[[ 3.68446

[[3.02060629 3.14565385]]
261
[[ 3.31894423 -3.45620085]]
[[3.3261527  3.52687683]]
259
[[ 3.66494526 -3.67831102]]
[[3.68387272 3.83585419]]
262
[[ 3.33099549 -3.40950066]]
[[3.35624465 3.50327597]]
256
[[ 3.1061595  -3.13441982]]
[[3.02329013 3.12192164]]
260
[[ 3.69771779 -3.65779738]]
[[3.70042119 3.78512819]]
263
[[ 3.37885212 -3.36930544]]
[[3.33963886 3.53551371]]
257
[[ 3.05003813 -3.20125214]]
[[3.0289756 3.1242272]]
261
[[ 3.65569188 -3.61093066]]
[[3.72528871 3.86418733]]
258
[[ 3.05246388 -3.18797487]]
[[3.04449465 3.10665685]]
264
[[ 3.39639057 -3.36236922]]
[[3.35542727 3.52331321]]
262
[[ 3.65902771 -3.64392906]]
[[3.6868839  3.86492388]]
259
[[ 3.04399357 -3.14085584]]
[[3.05208957 3.14165548]]
265
[[ 3.43419023 -3.35232194]]
[[3.38012254 3.52240182]]
263
[[ 3.65632238 -3.61189793]]
[[3.74699012 3.90517852]]
260
[[ 3.02565776 -3.11008505]]
[[3.06132168 3.15297459]]
266
[[ 3.42289553 -3.32055016]]
[[3.41394703 3.47552073]]
264
261
[[ 2.9801066  -3.05674402]]
[[ 3.6325557

303
[[ 3.17687994 -3.25151056]]
[[3.20402312 3.31801797]]
306
[[ 3.88027489 -3.79994523]]
[[3.79715344 3.87414896]]
308
[[ 3.23671346 -3.33758825]]
[[3.35734448 3.45220935]]
304
[[ 3.19572985 -3.30385075]]
[[3.1833452  3.27804511]]
307
[[ 3.80996424 -3.83360972]]
[[3.80979344 3.836368  ]]
309
[[ 3.27718327 -3.32145208]]
[[3.29555023 3.47629988]]
305
[[ 3.16786433 -3.31182832]]
[[3.22682704 3.27974455]]
308
[[ 3.85841317 -3.85069239]]
[[3.76387528 3.87418021]]
310
[[ 3.26184464 -3.34805404]]
[[3.26758676 3.48543201]]
306
[[ 3.17795552 -3.31016479]]
[[3.17890315 3.3113887 ]]
309
[[ 3.88150025 -3.80351942]]
[[3.74449309 3.87073294]]
311
[[ 3.28478687 -3.37318848]]
[[3.24597826 3.46127426]]
307
[[ 3.19053789 -3.30875625]]
[[3.20541212 3.34959923]]
310
[[ 3.84888233 -3.81848308]]
[[3.75406674 3.86705344]]
312
[[ 3.29143968 -3.43883782]]
[[3.29446907 3.47892846]]
308
[[ 3.13207166 -3.30229724]]
[[3.16653845 3.31705719]]
311
[[ 3.8724862  -3.80437005]]
[[3.78655208 3.86120497]]
313
[[ 3.28286

[[3.17480933 3.28103462]]
356
[[ 3.21616981 -3.25967516]]
[[3.24833111 3.35962872]]
354
[[ 3.69053629 -3.78430393]]
[[3.87639313 3.88062233]]
349
[[ 3.26739021 -3.25723459]]
[[3.21932132 3.31038405]]
357
[[ 3.18227512 -3.25598351]]
[[3.19861141 3.32475865]]
355
[[ 3.6841972  -3.72299826]]
[[3.82120389 3.91804554]]
358
[[ 3.16071544 -3.26190141]]
[[3.19246742 3.27598001]]
350
[[ 3.22669156 -3.30356368]]
[[3.21960895 3.25034578]]
359
[[ 3.14200584 -3.24490543]]
356
[[ 3.68104997 -3.7536794 ]]
[[3.81410219 3.90562715]]
[[3.23248721 3.29171793]]
351
[[ 3.28043466 -3.26476708]]
[[3.25008125 3.26006257]]
357
[[ 3.62965213 -3.80177989]]
[[3.77636199 3.91548519]]
360
[[ 3.16722805 -3.20788471]]
[[3.2347207  3.27475953]]
352
[[ 3.28268304 -3.23821565]]
[[3.26391713 3.24313192]]
361
[[ 3.18412129 -3.28674437]]
[[3.1830572  3.26593967]]
358
[[ 3.62748436 -3.78929793]]
[[3.71786915 3.91975096]]
353
[[ 3.28438796 -3.24107801]]
[[3.22298013 3.22047431]]
359
[[ 3.62750415 -3.77653815]]
[[3.74478014 3

395
[[ 3.14592429 -3.2210873 ]]
[[3.24999076 3.44325394]]
402
[[ 3.13346201 -3.03953569]]
[[3.12276133 3.13069685]]
403
[[ 3.65680222 -3.51716893]]
[[3.47352982 3.7927638 ]]
396
[[ 3.17362783 -3.30996724]]
[[3.24581215 3.42031194]]
403
[[ 3.13927275 -3.06604124]]
[[3.13647408 3.16460159]]
397
[[ 3.18428246 -3.29795871]]
[[3.27763438 3.39469174]]
404
[[ 3.66509432 -3.50182791]]
[[3.50957181 3.76569378]]
404
[[ 3.10198154 -3.08152763]]
[[3.1410804  3.22546823]]
398
[[ 3.15567713 -3.25186777]]
[[3.31148801 3.39198413]]
405
[[ 3.61841703 -3.54803167]]
[[3.51201233 3.77072656]]
399
[[ 3.12870372 -3.2702186 ]]
[[3.30652495 3.357712  ]]
405
[[ 3.09762327 -3.04511808]]
[[3.1141799  3.19398107]]
406
[[ 3.64306847 -3.58858244]]
[[3.47910657 3.78668458]]
400
[[ 3.15923837 -3.24352522]]
[[3.31800539 3.40955799]]
406
[[ 3.06730799 -3.04062193]]
[[3.08402425 3.17507889]]
407
[[ 3.66005481 -3.5717695 ]]
[[3.46676065 3.72590822]]
401
[[ 3.15833696 -3.26493474]]
[[3.32943591 3.40860954]]
407
[[ 3.06133

[[2.88099465 3.14009874]]
449
[[ 3.58584175 -3.5316802 ]]
[[3.57339595 3.54169703]]
444
[[ 3.1689893 -3.4644141]]
[[3.34768019 3.33567498]]
449
[[ 2.94688284 -3.03916459]]
[[2.87810772 3.15043358]]
450
[[ 3.62737552 -3.60681689]]
[[3.63442338 3.51053278]]
445
[[ 3.1460681  -3.43580449]]
[[3.34411512 3.39672564]]
450
[[ 2.99707666 -3.04816981]]
[[2.90304259 3.1863718 ]]
451
[[ 3.60085928 -3.5394384 ]]
[[3.58543562 3.51283351]]
451
[[ 3.05053521 -3.05108922]]
[[2.910691   3.14657478]]
446
[[ 3.12087405 -3.37229806]]
[[3.33171703 3.4235887 ]]
452
[[ 3.59423533 -3.56317273]]
[[3.6363142  3.58316418]]
447
[[ 3.15979164 -3.37851652]]
[[3.31867777 3.44613644]]
452
[[ 3.06193353 -3.05135028]]
[[2.97106243 3.15551918]]
453
[[ 3.58783623 -3.56783309]]
[[3.61787606 3.61434961]]
448
[[ 3.20959972 -3.37195844]]
[[3.22610683 3.41986009]]
453
[[ 3.096729   -3.08442786]]
[[2.97125578 3.17176941]]
454
[[ 3.60028819 -3.59618604]]
[[3.6615502  3.69478044]]
449
[[ 3.23236908 -3.39450798]]
[[3.22402162 3.3

490
[[ 3.27994413 -3.16815046]]
[[3.17732459 3.49861625]]
496
497
[[ 3.30935777 -3.33361504]]
[[3.28923541 3.34098181]]
[[ 3.50754765 -3.72147455]]
[[3.61910162 3.75713054]]
491
[[ 3.32291389 -3.18852606]]
[[3.17077474 3.48408701]]
497
[[ 3.27358678 -3.37039374]]
498
[[3.28397535 3.38486445]]
[[ 3.49791322 -3.70987468]]
[[3.65317181 3.7967369 ]]
492
[[ 3.30634602 -3.22605998]]
[[3.17367581 3.49211893]]
498
[[ 3.29070559 -3.41697184]]
[[3.25555016 3.40913024]]
499
[[ 3.51660692 -3.74321742]]
[[3.64425708 3.79530301]]
493
[[ 3.23881939 -3.21578484]]
[[3.1484178  3.42444963]]
499
[[ 3.28576145 -3.43374171]]
[[3.22073258 3.40638423]]
494
[[ 3.2284487 -3.2494102]]
[[3.19891967 3.38798517]]
495
[[ 3.22907955 -3.24172137]]
[[3.26362356 3.37884369]]
496
[[ 3.26180121 -3.30050297]]
[[3.23336348 3.40705908]]
497
[[ 3.23898635 -3.28133049]]
[[3.27456723 3.44319873]]
498
[[ 3.21813507 -3.27131614]]
[[3.25285377 3.45583926]]
499
[[ 3.26640106 -3.27245246]]
[[3.24786988 3.47057907]]
0
[[ 3.26040051 

[[3.69248348 3.83548964]]
43
[[ 3.37912737 -3.52836019]]
[[3.37716274 3.6867784 ]]
42
[[ 3.34035606 -3.25913232]]
[[3.17341006 3.27681252]]
43
[[ 3.5421172  -3.70976768]]
[[3.65648376 3.82217534]]
44
[[ 3.39158719 -3.53244647]]
[[3.2629991  3.69086591]]
43
[[ 3.37764839 -3.19919753]]
[[3.24901772 3.25124884]]
44
[[ 3.55487806 -3.66283059]]
[[3.67930663 3.81380538]]
45
[[ 3.4068785  -3.54616229]]
[[3.28044005 3.69931183]]
44
[[ 3.3512029  -3.26241965]]
[[3.25319492 3.27402662]]
45
[[ 3.58769931 -3.66006892]]
[[3.65592706 3.8367198 ]]
46
[[ 3.429186   -3.55510689]]
[[3.29640728 3.75810418]]
45
[[ 3.3160238  -3.28392386]]
[[3.24126478 3.32957961]]
46
[[ 3.62396424 -3.59861513]]
[[3.65083388 3.83355696]]
47
[[ 3.45433621 -3.5637325 ]]
[[3.32225023 3.74819584]]
46
[[ 3.32296555 -3.3005523 ]]
[[3.25621107 3.24350792]]
47
[[ 3.62846717 -3.60797425]]
[[3.66705823 3.79686174]]
48
[[ 3.47916769 -3.55990465]]
[[3.35837928 3.74711735]]
47
[[ 3.26964676 -3.32553105]]
[[3.32838126 3.26947526]]
48
[[

[[3.50264853 3.76641056]]
90
[[ 3.70230757 -3.75222177]]
[[3.75008152 3.68754941]]
90
[[ 3.39247545 -3.36735175]]
[[3.54562278 3.60644654]]
92
[[ 3.71960835 -3.49813557]]
[[3.58752391 3.78826418]]
91
[[ 3.73379613 -3.78210097]]
[[3.71756057 3.73164669]]
91
93
[[ 3.41577955 -3.32629506]]
[[3.5038771  3.63443139]]
[[ 3.69053308 -3.50139147]]
[[3.59362385 3.78821525]]
92
[[ 3.7120206  -3.76405087]]
[[3.71064455 3.73192073]]
92
[[ 3.40384026 -3.35398566]]
[[3.54064369 3.60926363]]
94
[[ 3.66875093 -3.47861404]]
[[3.6133525  3.77252814]]
93
[[ 3.74187878 -3.78818489]]
[[3.72831195 3.74379816]]
93
[[ 3.42800068 -3.40393936]]
[[3.48889983 3.61820448]]
95
[[ 3.64686741 -3.49880359]]
[[3.61230829 3.73650851]]
94
[[ 3.7635791  -3.79547431]]
[[3.71296512 3.76306145]]
94
[[ 3.43911659 -3.44745577]]
[[3.43335071 3.61336243]]
96
[[ 3.63492195 -3.47616264]]
[[3.61393198 3.78011611]]
95
[[ 3.76050248 -3.76575277]]
[[3.67933186 3.8123364 ]]
95
[[ 3.45811873 -3.48324711]]
[[3.44344925 3.61529379]]
96
[[

[[3.42252123 3.73887877]]
138
[[ 3.55287023 -3.5989625 ]]
[[3.5160362  3.58753978]]
138
[[ 3.38813977 -3.58768553]]
[[3.58666509 3.76945425]]
138
[[ 3.45606442 -3.57158725]]
[[3.45734446 3.74901935]]
139
[[ 3.53823798 -3.58830521]]
[[3.59603743 3.64428722]]
139
[[ 3.39786512 -3.60540845]]
[[3.54357478 3.73260898]]
139
[[ 3.45612194 -3.54786503]]
[[3.4108588  3.80597931]]
140
[[ 3.39818558 -3.63490739]]
[[3.53637403 3.75137105]]
140
[[ 3.51876897 -3.55055598]]
[[3.61442831 3.61883066]]
140
[[ 3.46366935 -3.5875058 ]]
[[3.44578491 3.7836768 ]]
141
[[ 3.47631303 -3.61610725]]
[[3.51595255 3.72760542]]
141
[[ 3.56006197 -3.60166102]]
[[3.61854209 3.59712545]]
141
[[ 3.40328454 -3.69346852]]
[[3.47563936 3.7888421 ]]
142
[[ 3.42842365 -3.59190614]]
[[3.56608641 3.70273852]]
142
[[ 3.60921018 -3.62312978]]
[[3.58933007 3.51873761]]
142
[[ 3.39447571 -3.65307335]]
[[3.51548582 3.82308143]]
143
[[ 3.35610307 -3.52517276]]
[[3.57026787 3.65526401]]
143
[[ 3.58010634 -3.58188026]]
[[3.56756879 3

185
[[ 3.62502297 -3.62298977]]
[[3.56898106 3.80091255]]
184
[[ 3.4274864  -3.54509391]]
[[3.57713579 3.70099641]]
186
[[ 3.28935247 -3.44331095]]
[[3.25304502 3.5262056 ]]
186
[[ 3.66196019 -3.57510006]]
[[3.61317384 3.79064147]]
185
[[ 3.40867563 -3.58501011]]
[[3.55368311 3.72389765]]
187
[[ 3.27719904 -3.44675654]]
[[3.21821506 3.46099358]]
186
[[ 3.3803911  -3.55069703]]
[[3.60887351 3.73082078]]
187
[[ 3.67056316 -3.59763769]]
[[3.61219688 3.75376863]]
188
[[ 3.25999233 -3.42514918]]
[[3.25381896 3.47405017]]
187
[[ 3.34594548 -3.50337199]]
[[3.61498457 3.70400124]]
188
[[ 3.68304708 -3.62690202]]
[[3.57290954 3.79294589]]
189
[[ 3.27534321 -3.39426465]]
[[3.28991229 3.45614754]]
188
[[ 3.37538203 -3.56413797]]
[[3.59508294 3.7042102 ]]
190
[[ 3.29050494 -3.42369184]]
189
[[3.28585455 3.46435357]]
[[ 3.6983337  -3.58994355]]
[[3.55838267 3.7593568 ]]
189
[[ 3.38186694 -3.61736749]]
[[3.61107021 3.66853395]]
190
[[ 3.66257124 -3.61465277]]
[[3.61420084 3.67720186]]
191
[[ 3.29348

[[3.46745849 3.60922843]]
234
[[ 3.28858671 -3.35256389]]
[[3.19926456 3.58029062]]
232
[[ 3.62914236 -3.75030166]]
[[3.65659532 3.73614939]]
231
[[ 3.64898564 -3.64698776]]
[[3.4876585  3.60330266]]
235
[[ 3.30226919 -3.40698795]]
[[3.23563634 3.5411815 ]]
233
[[ 3.64772105 -3.71115499]]
[[3.69302612 3.78979014]]
232
[[ 3.66216947 -3.59224337]]
[[3.49092776 3.59113318]]
236
[[ 3.30377259 -3.37422734]]
[[3.25887278 3.54850447]]
233
[[ 3.67430539 -3.61329634]]
[[3.51370025 3.63660513]]
234
[[ 3.65518782 -3.71660417]]
[[3.68759496 3.77471701]]
237
[[ 3.33499959 -3.40339067]]
[[3.28182287 3.53491673]]
234
[[ 3.62874848 -3.59517661]]
[[3.53179043 3.66673274]]
238
[[ 3.33410508 -3.38315228]]
[[3.29112068 3.53745648]]
235
[[ 3.65834116 -3.68285965]]
[[3.73527191 3.76805127]]
235
[[ 3.63214837 -3.55885902]]
[[3.55772055 3.7459343 ]]
236
[[ 3.68661597 -3.68175596]]
[[3.7381342  3.79701938]]
239
[[ 3.31934505 -3.41884132]]
[[3.30630179 3.57339762]]
236
[[ 3.57068988 -3.55961534]]
[[3.5904133  3

278
[[ 3.79195481 -3.84501341]]
[[3.69476057 3.98144555]]
281
[[ 3.37802419 -3.50177508]]
[[3.44689103 3.54076834]]
279
[[ 3.59557729 -3.62459051]]
[[3.7170944  3.66169735]]
279
[[ 3.80623409 -3.88125875]]
[[3.71737333 4.01630257]]
282
[[ 3.36839319 -3.49162743]]
[[3.47736693 3.5820444 ]]
280
[[ 3.59736567 -3.64065357]]
[[3.6716052  3.66565562]]
283
[[ 3.37072923 -3.52067599]]
[[3.50367333 3.63478221]]
280
[[ 3.80666482 -3.89847687]]
[[3.70947375 4.01858412]]
281
[[ 3.66835882 -3.6337297 ]]
[[3.64450136 3.67257908]]
284
[[ 3.40859616 -3.5301736 ]]
[[3.54006136 3.65355508]]
281
[[ 3.83013066 -3.880549  ]]
[[3.67999562 4.02072568]]
282
[[ 3.6780726  -3.56652179]]
[[3.63132654 3.67373594]]
285
[[ 3.40167058 -3.54792564]]
[[3.50424814 3.64432397]]
282
[[ 3.83866419 -3.88602233]]
[[3.75369138 4.02715264]]
283
[[ 3.70547566 -3.5552215 ]]
[[3.60665724 3.67249568]]
283
[[ 3.85561687 -3.90334573]]
[[3.77993509 4.03709649]]
286
[[ 3.3481873  -3.59304422]]
[[3.49725614 3.63741248]]
284
[[ 3.72804

[[3.66612232 3.95280855]]
326
[[ 3.67118607 -3.56742036]]
[[3.49885068 3.51849462]]
327
[[ 3.42536452 -3.57275513]]
[[3.41788284 3.54599229]]
327
[[ 3.64123752 -3.91058967]]
[[3.65875382 3.9856642 ]]
327
[[ 3.61514425 -3.52644353]]
[[3.49492219 3.57715735]]
328
[[ 3.63299436 -3.89676007]]
[[3.65974776 3.97273279]]
328
[[ 3.40224836 -3.59862795]]
[[3.44568217 3.5882495 ]]
328
[[ 3.56651323 -3.5433093 ]]
[[3.49347916 3.57641184]]
329
[[ 3.66045334 -3.97718313]]
[[3.65337302 4.04017581]]
329
[[ 3.42575864 -3.6067858 ]]
[[3.46315288 3.56717943]]
329
[[ 3.54699742 -3.49992365]]
[[3.48586076 3.63020917]]
330
[[ 3.66426713 -3.96249899]]
[[3.62942537 4.01771548]]
330
330
[[ 3.42225115 -3.5801139 ]]
[[3.45287316 3.55018028]]
[[ 3.51620629 -3.43066005]]
[[3.52753419 3.66845114]]
331
[[ 3.64218254 -3.99980408]]
[[3.68532405 4.02119008]]
331
[[ 3.43231683 -3.56684156]]
[[3.43522669 3.49274618]]
331
[[ 3.56803342 -3.402655  ]]
[[3.52059505 3.65338511]]
332
[[ 3.65174183 -3.9796281 ]]
[[3.68389911 4

374
[[ 3.46663196 -3.40039843]]
[[3.40897778 3.35184962]]
374
[[ 3.75981924 -3.72405385]]
[[3.60598655 3.77274324]]
373
[[ 3.46005041 -3.42284495]]
[[3.38021197 3.48983554]]
375
[[ 3.47159666 -3.41373311]]
[[3.41314219 3.39941053]]
375
[[ 3.72032822 -3.71120782]]
[[3.64552318 3.86507888]]
374
[[ 3.46284831 -3.48178549]]
[[3.4173538  3.50196774]]
376
[[ 3.4639539  -3.41780625]]
[[3.42726159 3.4198162 ]]
376
[[ 3.70630824 -3.72758009]]
[[3.66536033 3.8980046 ]]
375
[[ 3.44482243 -3.5051296 ]]
[[3.43708317 3.49312781]]
377
[[ 3.42957659 -3.42200588]]
[[3.41643543 3.43287062]]
377
[[ 3.73624536 -3.69720055]]
[[3.68168286 3.81330926]]
376
[[ 3.43917051 -3.52272978]]
[[3.46193774 3.4971975 ]]
378
378
[[ 3.74225196 -3.72546056]]
[[ 3.42005588 -3.40812313]]
[[3.39483315 3.48836392]]
[[3.7267715  3.82341345]]
377
[[ 3.43570787 -3.55430009]]
[[3.47018154 3.53262046]]
379
[[ 3.42701128 -3.38709825]]
[[3.42410005 3.42541704]]
379
[[ 3.741658   -3.70867989]]
[[3.70267923 3.8513438 ]]
378
[[ 3.47352

[[3.7818957  3.73543235]]
420
[[ 3.57064361 -3.30208704]]
[[3.57972583 3.68561001]]
422
[[ 3.65823073 -3.59133296]]
[[3.74669285 3.74728602]]
421
[[ 3.58789017 -3.33126301]]
[[3.61605948 3.66895945]]
421
[[ 3.26128888 -3.48222427]]
[[3.29580908 3.54840992]]
423
[[ 3.69236162 -3.6357903 ]]
[[3.74788702 3.77272226]]
422
[[ 3.51292403 -3.37080483]]
[[3.55516562 3.70269723]]
422
[[ 3.30046299 -3.52279076]]
[[3.32168284 3.53382029]]
424
[[ 3.71572779 -3.63225809]]
[[3.74785179 3.73777496]]
423
[[ 3.49950224 -3.33349506]]
[[3.52815241 3.71354146]]
425
423
[[ 3.28161515 -3.52310301]]
[[3.34629256 3.52715999]]
[[ 3.73087292 -3.61550781]]
[[3.7694037  3.69362189]]
424
[[ 3.49806223 -3.38696458]]
[[3.56319632 3.73967673]]
424
[[ 3.25197151 -3.47398855]]
[[3.3066618  3.59334835]]
426
[[ 3.71064579 -3.64214672]]
[[3.72875119 3.70758307]]
425
[[ 3.51258961 -3.3636976 ]]
[[3.57418687 3.77253429]]
425
[[ 3.2740494  -3.45158136]]
[[3.30886258 3.61023567]]
427
[[ 3.68147223 -3.70441657]]
[[3.74558654 3

469
[[ 3.43506492 -3.623193  ]]
[[3.56710552 3.72877998]]
467
[[ 3.29611814 -3.40191321]]
[[3.33551101 3.56591847]]
468
[[ 3.64818034 -3.67865716]]
[[3.48021829 3.84726025]]
470
[[ 3.40198116 -3.63779331]]
[[3.54349009 3.74383426]]
468
[[ 3.28504655 -3.30712551]]
[[3.31247189 3.61476454]]
469
[[ 3.63985354 -3.71542152]]
[[3.43280558 3.85010678]]
471
[[ 3.3433359  -3.63936336]]
[[3.61410286 3.77452826]]
469
[[ 3.26767277 -3.329337  ]]
[[3.30535924 3.60039828]]
470
[[ 3.62285416 -3.69370816]]
[[3.42519496 3.85379059]]
472
[[ 3.39669598 -3.67337352]]
[[3.5601495  3.77868944]]
470
[[ 3.28833287 -3.35254383]]
[[3.35640798 3.55587374]]
471
[[ 3.60743696 -3.66119971]]
[[3.42186067 3.86674322]]
473
[[ 3.40377041 -3.65284859]]
[[3.53990402 3.7825377 ]]
472
[[ 3.59931889 -3.65177781]]
[[3.46406403 3.81330645]]
471
[[ 3.30309839 -3.36329275]]
[[3.33244897 3.516145  ]]
474
[[ 3.4452223  -3.62767213]]
[[3.55096694 3.78740324]]
472
[[ 3.26908903 -3.31486933]]
[[3.29748093 3.46915891]]
473
[[ 3.58203

15
[[ 3.60727117 -3.53468455]]
[[3.70099184 3.70486761]]
15
[[ 3.29815424 -3.45266633]]
[[3.36710053 3.503162  ]]
16
[[ 3.6758984  -3.55603979]]
[[3.6766393  3.70940921]]
17
[[ 3.16741605 -3.27967997]]
[[3.27143423 3.43950795]]
16
[[ 3.27151313 -3.42646411]]
[[3.40706273 3.51976059]]
17
[[ 3.62955094 -3.58429503]]
[[3.60941    3.66777941]]
18
[[ 3.19211391 -3.27297699]]
[[3.24086248 3.43057613]]
17
[[ 3.28181034 -3.39441201]]
[[3.38205173 3.54064613]]
18
[[ 3.61427947 -3.53614769]]
[[3.6302343  3.67096768]]
19
[[ 3.18600932 -3.27088624]]
[[3.22353422 3.37790625]]
18
[[ 3.27069315 -3.35415525]]
[[3.41989247 3.52174876]]
20
[[ 3.18160277 -3.31905791]]
[[3.27472791 3.41761165]]
19
[[ 3.6311704  -3.49787663]]
[[3.62306945 3.71801187]]
19
[[ 3.31340539 -3.2857408 ]]
[[3.41179404 3.53089483]]
21
[[ 3.19892415 -3.32675172]]
[[3.2820978  3.45315291]]
20
[[ 3.63593134 -3.52946808]]
[[3.60743385 3.72947826]]
20
[[ 3.37732435 -3.27606544]]
[[3.45053701 3.51894594]]
22
[[ 3.20325075 -3.33092989]]


63
[[ 3.4218021  -3.38623123]]
[[3.37116975 3.49729995]]
65
[[ 3.32952973 -3.41906507]]
[[3.25227384 3.40682526]]
63
[[ 3.74669836 -3.52147339]]
[[3.60110873 3.66120917]]
64
[[ 3.43977682 -3.38790669]]
[[3.35229221 3.51417797]]
66
[[ 3.31945067 -3.41520518]]
[[3.22237262 3.45173002]]
64
[[ 3.71924273 -3.53315941]]
[[3.58599553 3.67263283]]
65
[[ 3.43690802 -3.36996157]]
[[3.30663979 3.50637739]]
66
67
[[ 3.29539256 -3.41852933]]
[[ 3.40975193 -3.39164782]]
[[3.28365386 3.51493955]]
[[3.28305312 3.46937946]]
65
[[ 3.65117984 -3.53704767]]
[[3.58629378 3.62831326]]
68
[[ 3.34925682 -3.44585406]]
[[3.29769599 3.49193293]]
67
[[ 3.44581232 -3.39215739]]
[[3.30258578 3.51607048]]
66
[[ 3.58214948 -3.54594587]]
[[3.52939226 3.63675354]]
69
[[ 3.35587025 -3.49241539]]
[[3.29685846 3.49247662]]
68
[[ 3.41881703 -3.41381154]]
[[3.34213179 3.51300465]]
67
[[ 3.57709736 -3.50344009]]
[[3.49161417 3.60334065]]
70
[[ 3.32989854 -3.47140898]]
[[3.27554255 3.52578986]]
69
[[ 3.3978803  -3.43500429]]


[[3.41680081 3.57465266]]
112
[[ 3.34116011 -3.36105003]]
[[3.32974286 3.60064236]]
110
[[ 3.75017127 -3.70180072]]
[[3.63357818 3.95947018]]
113
[[ 3.39825025 -3.42266914]]
[[3.43171126 3.5881355 ]]
113
[[ 3.38370236 -3.42808895]]
[[3.33623436 3.65237832]]
111
[[ 3.71285361 -3.69094517]]
[[3.62793465 3.89531685]]
114
[[ 3.39314156 -3.4772125 ]]
[[3.35062591 3.66177561]]
114
[[ 3.40801205 -3.40376261]]
[[3.45176733 3.49753046]]
112
[[ 3.69481573 -3.66086535]]
[[3.61721726 3.88336212]]
115
[[ 3.39438246 -3.40470607]]
[[3.41187829 3.63330269]]
115
[[ 3.40883519 -3.44549345]]
[[3.42115826 3.46979342]]
113
[[ 3.72007939 -3.61597672]]
[[3.63224511 3.88431385]]
116
[[ 3.38455771 -3.40366781]]
[[3.44778056 3.63525429]]
116
[[ 3.41494507 -3.45397061]]
[[3.46507486 3.45181606]]
114
[[ 3.68908363 -3.64429323]]
[[3.66824535 3.84688187]]
117
[[ 3.38666749 -3.40638021]]
[[3.44407596 3.6068421 ]]
117
[[ 3.3998966  -3.45293554]]
[[3.40284595 3.4668697 ]]
115
[[ 3.67499135 -3.64776118]]
[[3.64659976 3

[[ 3.694073   -3.61448228]]
[[3.68443879 3.88418487]]
159
[[ 3.31111317 -3.45384832]]
[[3.34993334 3.3566446 ]]
160
[[ 3.75668915 -3.5571604 ]]
[[3.46965057 3.75075828]]
158
[[ 3.67045025 -3.56999289]]
[[3.67184352 3.86220886]]
160
[[ 3.33941006 -3.45351775]]
[[3.32081854 3.35421012]]
161
[[ 3.73084339 -3.58998751]]
[[3.55095567 3.78555296]]
159
[[ 3.67487786 -3.57492199]]
[[3.68578202 3.84055431]]
162
[[ 3.74191397 -3.60861703]]
[[3.53525686 3.8153092 ]]
161
[[ 3.29746537 -3.45393831]]
[[3.27934094 3.34799123]]
160
[[ 3.64915499 -3.58531878]]
[[3.63555709 3.84695528]]
163
[[ 3.64980516 -3.63514156]]
[[3.53038435 3.81873061]]
162
[[ 3.29429736 -3.50088656]]
[[3.26911194 3.32950049]]
161
[[ 3.59999937 -3.64540583]]
[[3.6242187 3.8508515]]
164
[[ 3.64828981 -3.61469189]]
[[3.52592014 3.84646422]]
163
[[ 3.28581298 -3.47948879]]
[[3.31276975 3.3130543 ]]
162
165
[[ 3.68378913 -3.54806512]]
[[ 3.67755232 -3.63460508]]
[[3.66732708 3.84323892]]
[[3.54191623 3.8019456 ]]
163
[[ 3.67575387 -3

[[3.18439555 3.41682529]]
208
[[ 3.72778717 -3.59919734]]
[[3.62885088 3.63886724]]
204
[[ 3.61837297 -3.65830379]]
[[3.69326328 3.79399806]]
205
[[ 3.62693921 -3.66481831]]
[[3.68552056 3.76522655]]
206
[[ 3.17927806 -3.30788956]]
[[3.1972752  3.43718422]]
209
[[ 3.6807238  -3.58148404]]
[[3.67244219 3.6133695 ]]
206
[[ 3.62797263 -3.71684039]]
[[3.6762906  3.78762065]]
210
[[ 3.69206076 -3.56571865]]
[[3.63038654 3.6524386 ]]
207
[[ 3.17762242 -3.28905492]]
[[3.11888864 3.45628734]]
207
[[ 3.63752658 -3.72025918]]
[[3.68411914 3.79506101]]
211
[[ 3.67391148 -3.52047811]]
[[3.63134292 3.67911239]]
208
[[ 3.1732211  -3.23575028]]
[[3.14360479 3.46986563]]
208
[[ 3.67748966 -3.75696965]]
[[3.69488273 3.79836936]]
212
[[ 3.66027799 -3.5388479 ]]
[[3.62955415 3.66115352]]
209
[[ 3.12382521 -3.27207979]]
[[3.176644  3.3689481]]
209
[[ 3.6479685  -3.76449268]]
[[3.72836421 3.80190548]]
213
[[ 3.62113345 -3.54498482]]
[[3.59636421 3.67739279]]
210
[[ 3.12308371 -3.22276871]]
[[3.20090662 3.3

254
[[ 3.61105762 -3.70499768]]
[[3.58137214 3.74697355]]
252
[[ 3.18246376 -3.08352453]]
[[3.1138099  3.27135883]]
253
[[ 3.72063287 -3.74941952]]
[[3.67112464 3.71655808]]
255
[[ 3.66070175 -3.6862784 ]]
[[3.57081408 3.72522605]]
253
[[ 3.17073438 -3.03666185]]
[[3.09406078 3.24450432]]
254
[[ 3.69430606 -3.73347764]]
[[3.64437743 3.67451203]]
256
[[ 3.60725041 -3.68394163]]
[[3.60784639 3.72483776]]
255
[[ 3.69248894 -3.75807496]]
[[3.62610463 3.68442883]]
254
[[ 3.18164959 -3.05446889]]
[[3.05717004 3.19853523]]
257
[[ 3.61804072 -3.71007127]]
[[3.57998541 3.71993344]]
256
[[ 3.63893684 -3.77963769]]
[[3.62118079 3.68519795]]
255
[[ 3.21682247 -3.1243998 ]]
[[3.02233164 3.21936093]]
258
[[ 3.63340227 -3.71695131]]
[[3.57684661 3.73690713]]
257
[[ 3.59654685 -3.70496799]]
[[3.65404278 3.74464654]]
256
[[ 3.16581441 -3.05637518]]
[[3.03495089 3.23258223]]
259
[[ 3.63106855 -3.69841754]]
[[3.52166067 3.74583866]]
258
[[ 3.61836805 -3.74704161]]
[[3.66319495 3.67654668]]
257
[[ 3.18105

[[ 3.6923135  -3.76520583]]
[[3.1409983  3.22847982]]
[[3.53801781 3.6065695 ]]
299
[[ 3.08519014 -3.15738391]]
[[3.1279521  3.23039783]]
300
[[ 3.81257755 -3.81444836]]
[[3.75765617 3.88955647]]
303
[[ 3.65794727 -3.77470704]]
[[3.52324195 3.59271232]]
300
[[ 3.07874795 -3.17394696]]
[[3.16899733 3.22329129]]
301
[[ 3.8028713  -3.81638391]]
[[3.74081449 3.87392529]]
304
[[ 3.65756085 -3.75100953]]
[[3.52162025 3.57580216]]
301
[[ 3.12361747 -3.11055027]]
[[3.16929601 3.19541161]]
302
[[ 3.79495466 -3.76370758]]
[[3.77652144 3.88344699]]
305
[[ 3.60087665 -3.73786818]]
[[3.5244641  3.60107641]]
302
[[ 3.07630298 -3.11476654]]
[[3.15945031 3.12654822]]
303
[[ 3.75182451 -3.75776019]]
[[3.74127011 3.88271452]]
306
[[ 3.59105349 -3.75670596]]
[[3.52734903 3.61278387]]
303
[[ 3.06087068 -3.13211497]]
[[3.14841558 3.09943452]]
304
[[ 3.74637669 -3.72196082]]
[[3.77798977 3.8976515 ]]
307
[[ 3.60604819 -3.74730775]]
[[3.51899447 3.62467856]]
304
[[ 3.06444124 -3.09008779]]
[[3.18726779 3.073

347
[[ 3.88540988 -3.89285876]]
[[3.73998286 3.83851352]]
349
[[ 3.66756125 -3.67069114]]
[[3.65975711 3.85333063]]
348
[[ 3.89226119 -3.90201996]]
[[3.71098195 3.83627063]]
346
[[ 3.20471217 -3.190055  ]]
[[3.06561772 3.25222939]]
350
[[ 3.66498336 -3.63031694]]
[[3.67569114 3.84843596]]
349
347
[[ 3.92069725 -3.90811212]]
[[ 3.18298136 -3.17802311]]
[[3.76495825 3.83513579]]
[[3.05476989 3.26552117]]
351
[[ 3.66843125 -3.70962963]]
[[3.65567343 3.81795559]]
348
[[ 3.19826065 -3.15417898]]
[[3.0540999  3.23149126]]
350
[[ 3.94328985 -3.89443729]]
[[3.74581176 3.85489401]]
352
[[ 3.64117327 -3.66369761]]
[[3.64043237 3.86282799]]
349
[[ 3.21139029 -3.21962128]]
[[3.03374797 3.25425184]]
351
[[ 3.90864794 -3.87290088]]
[[3.74634307 3.86950854]]
353
[[ 3.60344971 -3.71224254]]
[[3.63745657 3.88354249]]
350
[[ 3.13319583 -3.23799403]]
[[3.04952067 3.26168299]]
352
[[ 3.92521973 -3.8948423 ]]
[[3.80579182 3.91873272]]
354
[[ 3.53378079 -3.72722807]]
[[3.65314178 3.87747248]]
351
[[ 3.10307

[[3.77882882 3.76536924]]
391
[[ 3.26849949 -3.28627903]]
[[3.14299668 3.32112963]]
395
[[ 4.01878819 -4.01060257]]
[[3.75284055 4.05211693]]
398
[[ 3.70460256 -3.81303401]]
[[3.79575665 3.75521089]]
392
[[ 3.25963959 -3.3055448 ]]
[[3.17219538 3.25834934]]
396
[[ 3.99469698 -4.00206171]]
[[3.83496527 4.06900451]]
399
[[ 3.71756171 -3.7899648 ]]
[[3.79780503 3.81607465]]
397
[[ 3.9294943  -4.00598154]]
[[3.7644448  4.07965613]]
393
[[ 3.28362192 -3.31980282]]
[[3.16329905 3.29126143]]
400
[[ 3.72510113 -3.77685556]]
[[3.7518245  3.77763329]]
398
[[ 3.9327834  -3.98816309]]
[[3.78117442 4.08876422]]
394
[[ 3.26506691 -3.34542125]]
[[3.17288814 3.2934781 ]]
401
[[ 3.70410739 -3.77567558]]
[[3.79533939 3.842769  ]]
399
[[ 3.91734335 -4.03349282]]
[[3.74568442 4.11314132]]
395
[[ 3.30259301 -3.3654854 ]]
[[3.13054813 3.28819247]]
402
[[ 3.69022181 -3.74706154]]
[[3.78969916 3.80362943]]
400
[[ 3.89984547 -4.02218253]]
[[3.7719134  4.11412227]]
396
[[ 3.38138605 -3.38575611]]
[[3.130651   3

[[ 4.12150858 -4.08470703]]
[[4.0393804  4.02710975]]
445
[[ 3.61855645 -3.75546776]]
[[3.59872492 3.73122492]]
442
[[ 4.06845553 -4.03328305]]
[[3.97838542 4.02048416]]
439
[[ 3.17471135 -3.31624456]]
[[3.21016658 3.28626165]]
446
[[ 3.64628381 -3.77731143]]
[[3.6427002  3.68673413]]
440
[[ 3.0946396 -3.3126586]]
[[3.15841578 3.2794218 ]]
443
[[ 4.05203585 -4.04565424]]
[[3.99441863 4.06990004]]
447
[[ 3.62147543 -3.79619933]]
[[3.60936057 3.67802922]]
441
[[ 3.10901785 -3.27673654]]
[[3.19374938 3.25202061]]
444
[[ 4.06023512 -4.08608044]]
[[4.05611886 4.05478334]]
448
[[ 3.62207813 -3.76013223]]
[[3.65694686 3.73333384]]
445
[[ 4.09561945 -4.11025964]]
[[4.00643502 4.08849347]]
442
[[ 3.15931358 -3.23447663]]
[[3.1845636 3.289505 ]]
449
[[ 3.67313064 -3.75225113]]
[[3.63813607 3.71429983]]
446
[[ 4.1183117  -4.02571387]]
[[3.99493199 4.05240332]]
443
[[ 3.15387225 -3.2607973 ]]
[[3.17468423 3.25465708]]
450
[[ 3.65373022 -3.71755822]]
[[3.67720814 3.68903825]]
447
[[ 4.11434027 -3.9

[[3.78405164 3.82566911]]
[[ 3.24189367 -3.13902174]]
[[3.32409726 3.44826846]]
488
[[ 3.85326923 -3.95314551]]
[[4.02874076 4.29855103]]
493
[[ 3.80813744 -3.78029307]]
[[3.76211252 3.88168059]]
487
[[ 3.24599509 -3.16867754]]
[[3.31640114 3.47048792]]
489
[[ 3.85157779 -3.98432749]]
[[4.04762061 4.24565168]]
488
[[ 3.25333093 -3.17061777]]
[[3.36906398 3.47377431]]
494
[[ 3.8329603  -3.76229002]]
[[3.73307065 3.86738044]]
490
[[ 3.8426911 -3.980765 ]]
[[4.07276749 4.19637152]]
489
[[ 3.20822904 -3.13149017]]
[[3.38308416 3.46699088]]
495
[[ 3.85913346 -3.74658801]]
[[3.7010617  3.87478197]]
491
[[ 3.85475421 -3.99944153]]
[[4.06916453 4.21765426]]
490
[[ 3.21913944 -3.1345526 ]]
[[3.40831262 3.42200524]]
496
[[ 3.88798619 -3.76553899]]
[[3.65385576 3.8813399 ]]
492
[[ 3.83772798 -4.01444383]]
[[4.06629241 4.25775889]]
491
[[ 3.20691254 -3.11401208]]
[[3.35216906 3.40120227]]
497
[[ 3.83765709 -3.78013464]]
[[3.69155397 3.89012952]]
492
[[ 3.22490986 -3.18320078]]
[[3.37524613 3.35864

[[3.16565666 3.28528394]]
36
[[ 4.00764078 -3.94919323]]
[[3.86287499 3.98503074]]
37
[[ 3.90600066 -3.97071594]]
[[3.79473919 3.98016226]]
38
[[ 3.13281621 -3.21544217]]
[[3.16806813 3.3342553 ]]
37
[[ 4.02567317 -4.007633  ]]
[[3.90685183 3.9798624 ]]
38
[[ 3.88973911 -3.9300723 ]]
[[3.7526772  3.95556323]]
39
[[ 3.14449165 -3.18835195]]
[[3.16265817 3.26900286]]
38
[[ 4.04120228 -4.00191319]]
[[3.8535016  3.91607013]]
39
[[ 3.93591055 -3.96101467]]
[[3.78786375 3.9275334 ]]
40
39
[[ 3.1738376  -3.18265183]]
[[ 4.00319049 -4.04746282]]
[[3.87785485 3.9356578 ]]
[[3.2074668  3.22010684]]
40
[[ 3.98641107 -3.96554443]]
[[3.76888186 3.91462717]]
40
[[ 4.01824851 -4.0308523 ]]
41
[[ 3.19512379 -3.20640306]]
[[3.21029906 3.20801052]]
[[3.88272934 3.99304611]]
41
[[ 3.98072483 -3.95337151]]
[[3.80422064 3.90206067]]
42
[[ 3.15753301 -3.21526785]]
[[3.27659341 3.1676929 ]]
41
[[ 4.04349885 -4.02789398]]
[[3.88047705 4.02251019]]
42
[[ 3.92558366 -3.94369541]]
[[3.82992993 3.92508264]]
43
[[

[[3.63912533 3.92194874]]
84
[[ 4.08388215 -4.17088048]]
[[4.12321734 4.23304454]]
85
[[ 3.28839866 -3.38333043]]
[[3.1760081  3.43509945]]
86
[[ 3.72426558 -3.87252166]]
[[3.6666971  3.89394854]]
86
[[ 3.298733   -3.41972823]]
[[3.14135706 3.39571917]]
85
[[ 4.09002758 -4.07798294]]
[[4.1092162  4.23263736]]
87
[[ 3.73008199 -3.84839268]]
[[3.70397593 3.87544767]]
87
[[ 3.28130827 -3.40632776]]
[[3.13250408 3.41290707]]
86
[[ 4.05992537 -4.12313234]]
[[4.12835709 4.19668182]]
88
[[ 3.7818756  -3.82863031]]
[[3.67603906 3.90359027]]
88
[[ 3.28103064 -3.34787354]]
[[3.18228922 3.43176796]]
87
[[ 4.08034271 -4.15710011]]
[[4.16075434 4.19129659]]
89
[[ 3.83065038 -3.85897728]]
[[3.65248787 3.92734357]]
89
[[ 3.27326815 -3.35623733]]
[[3.20061102 3.41197672]]
88
[[ 4.09513189 -4.18630557]]
[[4.09832054 4.21108873]]
90
[[ 3.3565325  -3.35895002]]
[[3.18078991 3.43463069]]
90
[[ 3.75627148 -3.83784365]]
[[3.61768691 3.95543171]]
89
[[ 4.06604515 -4.19085879]]
[[4.08044696 4.20624856]]
91
[[

131
[[ 4.12973743 -4.18799817]]
[[4.16002116 4.50519253]]
132
[[ 3.18532389 -3.44730443]]
[[3.13986202 3.42810751]]
134
[[ 3.85350572 -3.77073925]]
[[3.6806789  3.92621041]]
132
[[ 4.13715329 -4.15678665]]
[[4.14669412 4.52808548]]
133
[[ 3.16082512 -3.43887671]]
[[3.13461838 3.46261836]]
135
[[ 3.86346761 -3.79000096]]
[[3.69119977 3.95052808]]
133
[[ 4.14020567 -4.25888854]]
[[4.11836982 4.53947723]]
134
[[ 3.12412183 -3.46362697]]
[[3.19991046 3.44120053]]
136
[[ 3.87491425 -3.77242775]]
[[3.72148541 3.91719168]]
134
[[ 4.17070008 -4.18101527]]
[[4.1062247  4.55698468]]
135
[[ 3.15694796 -3.44920927]]
[[3.24146033 3.46272656]]
137
[[ 3.91778057 -3.77572382]]
[[3.70540367 3.89970237]]
135
[[ 4.13984425 -4.20028925]]
[[4.12530898 4.5786844 ]]
136
[[ 3.1724866  -3.43680704]]
[[3.17391118 3.47020538]]
138
[[ 3.87304826 -3.76913554]]
[[3.70624316 3.87257753]]
136
[[ 4.14844295 -4.20955087]]
[[4.15325245 4.59561947]]
137
[[ 3.12845701 -3.38933147]]
[[3.19789217 3.44998082]]
137
139
[[ 4.1

[[3.36081192 3.45087873]]
179
[[ 3.68358959 -3.81478312]]
[[3.69172664 3.89898924]]
179
[[ 4.22443931 -4.14905503]]
[[4.11737125 4.29996319]]
181
[[ 3.34092128 -3.32218336]]
[[3.35158767 3.47428035]]
180
[[ 3.69670273 -3.77489666]]
[[3.68135661 3.93262678]]
180
[[ 4.26946997 -4.18468549]]
[[4.14021855 4.27470248]]
182
[[ 3.33503847 -3.34562883]]
[[3.41708639 3.46217688]]
181
[[ 3.70496637 -3.78448541]]
[[3.7023277  3.90884912]]
183
[[ 3.33294821 -3.32604488]]
[[3.43510656 3.46809525]]
181
[[ 4.27979875 -4.15465255]]
[[4.14144808 4.21438246]]
182
[[ 3.68718058 -3.75470399]]
[[3.6869539  3.90754332]]
182
184
[[ 3.29925876 -3.29687581]]
[[3.42803347 3.46427913]]
[[ 4.28594739 -4.17234286]]
[[4.09554433 4.19729922]]
183
[[ 3.71285602 -3.7671108 ]]
[[3.66773301 3.92407392]]
185
[[ 3.33805333 -3.33459934]]
[[3.4604772  3.42102739]]
183
[[ 4.24164906 -4.13239582]]
[[4.09668982 4.16997267]]
184
[[ 3.69214831 -3.83396255]]
[[3.68419405 3.87430557]]
186
[[ 3.3696876 -3.3486046]]
[[3.44949088 3.4

226
[[ 4.1311261  -4.20236906]]
[[4.23361568 4.21477972]]
227
[[ 3.19659256 -3.26996515]]
[[3.16188449 3.2364757 ]]
227
[[ 3.72046445 -3.67756805]]
[[3.74198497 3.98983759]]
227
[[ 4.14916315 -4.19139794]]
[[4.23160651 4.24055312]]
228
[[ 3.20885517 -3.25606346]]
[[3.18522935 3.21575044]]
228
[[ 3.74343795 -3.63101382]]
[[3.7322509 4.007853 ]]
228
[[ 4.21455331 -4.17261821]]
[[4.21679954 4.26249611]]
229
[[ 3.23966897 -3.24420476]]
[[3.17609854 3.22299742]]
229
[[ 3.71897498 -3.65613672]]
[[3.72984259 3.9787186 ]]
229
[[ 4.21920604 -4.1787537 ]]
[[4.23842101 4.25951726]]
230
[[ 3.2584743  -3.27581072]]
[[3.17970179 3.27173439]]
230
[[ 3.7233051  -3.69019087]]
[[3.70147141 3.9676509 ]]
230
[[ 4.16415163 -4.18154143]]
[[4.23012434 4.26474096]]
231
[[ 3.22610115 -3.34391972]]
[[3.10151693 3.27860356]]
231
[[ 4.18042733 -4.19792601]]
[[4.21913503 4.28862783]]
231
[[ 3.67257636 -3.67681485]]
[[3.66570172 3.94341264]]
232
[[ 3.25921975 -3.36930044]]
[[3.1205297 3.3453423]]
232
[[ 3.64317398 

[[3.18400912 3.47745129]]
273
[[ 4.39529457 -4.2800272 ]]
[[4.48876795 4.6285521 ]]
274
[[ 3.6511939  -3.50351868]]
[[3.50238976 3.78298245]]
275
[[ 3.67347226 -3.53703163]]
[[3.47699121 3.81461358]]
275
[[ 3.17397419 -3.37352126]]
[[3.1510995  3.43990216]]
274
[[ 4.40003401 -4.30904062]]
[[4.46245479 4.59936367]]
276
[[ 3.67513993 -3.50066865]]
[[3.45155482 3.81472336]]
276
[[ 3.18814461 -3.34736608]]
[[3.19474824 3.46774331]]
275
[[ 4.44859317 -4.33023332]]
[[4.48712801 4.66255452]]
277
[[ 3.20867559 -3.30153685]]
[[3.14370197 3.46020292]]
277
[[ 3.70584873 -3.5539892 ]]
[[3.45987079 3.83818589]]
276
[[ 4.45684052 -4.34427324]]
[[4.50016934 4.64064507]]
278
[[ 3.22357076 -3.26119973]]
[[3.14160861 3.44194854]]
278
[[ 3.65230667 -3.4920482 ]]
[[3.5027691 3.8496435]]
277
[[ 4.43939729 -4.37259549]]
[[4.48311365 4.63840869]]
279
[[ 3.22474973 -3.32262414]]
[[3.09737003 3.45752455]]
279
[[ 3.68239708 -3.48894738]]
[[3.47302681 3.83028746]]
278
[[ 4.4428523  -4.38831628]]
[[4.4880391  4.6

319
[[ 4.34716661 -4.6193441 ]]
[[4.38461633 4.60553197]]
323
[[ 3.52213443 -3.50967983]]
[[3.50274969 3.63049871]]
321
[[ 3.1513311 -3.2076695]]
[[3.17475265 3.3261382 ]]
320
[[ 4.39180435 -4.53109915]]
[[4.38733335 4.61368479]]
324
[[ 3.47326671 -3.48960126]]
[[3.46311579 3.6563442 ]]
321
[[ 4.39498892 -4.51732909]]
[[4.34515345 4.63319874]]
322
[[ 3.13010154 -3.19751766]]
[[3.20168163 3.27518514]]
325
[[ 3.47480534 -3.51695458]]
[[3.46113731 3.59521524]]
322
[[ 4.47146884 -4.48426328]]
[[4.29703509 4.6327062 ]]
323
[[ 3.10289666 -3.21186719]]
[[3.19946821 3.27192524]]
326
[[ 3.49025543 -3.59985668]]
[[3.51928177 3.5296948 ]]
323
[[ 4.46522231 -4.47927646]]
[[4.2656285  4.57851417]]
324
[[ 3.08998462 -3.19945222]]
[[3.16839142 3.25778145]]
327
[[ 3.50002522 -3.56810952]]
[[3.47375917 3.51980029]]
324
[[ 4.4773826  -4.47035543]]
[[4.21333769 4.56364083]]
325
[[ 3.06910896 -3.15679897]]
[[3.13616938 3.24998375]]
328
[[ 3.47790192 -3.5460493 ]]
[[3.48919338 3.55075415]]
325
[[ 4.4884887

[[4.24055462 4.52328427]]
367
[[ 3.20712956 -3.20937816]]
[[3.19884309 3.28879566]]
371
[[ 3.52241752 -3.4674761 ]]
[[3.44887003 3.61421241]]
367
[[ 4.1293919  -4.23926729]]
[[4.21387924 4.54073821]]
368
[[ 3.21392923 -3.25976952]]
[[3.19275723 3.29482047]]
372
[[ 3.50129591 -3.44503615]]
[[3.44838857 3.60609592]]
368
[[ 4.13880539 -4.28251307]]
[[4.20711589 4.57621047]]
373
[[ 3.51374359 -3.45629197]]
[[3.46211003 3.69864288]]
369
[[ 4.15107739 -4.28357992]]
[[4.24066603 4.58630925]]
369
[[ 3.18818789 -3.26755361]]
[[3.15593507 3.26156893]]
374
[[ 3.55187078 -3.48288558]]
[[3.40392227 3.65068182]]
370
[[ 3.20433226 -3.28204899]]
[[3.17158449 3.28476995]]
370
[[ 4.10430231 -4.27035289]]
[[4.23597442 4.55789192]]
375
[[ 3.58339918 -3.51934049]]
[[3.43595379 3.62775187]]
371
[[ 3.20627961 -3.29874687]]
[[3.19479446 3.30867198]]
371
[[ 4.11524308 -4.23909569]]
[[4.22348296 4.49383641]]
376
[[ 3.5867866  -3.52413208]]
[[3.40298173 3.60515356]]
372
[[ 3.19229803 -3.25955396]]
[[3.19860961 3

414
[[ 3.36129599 -3.30315753]]
[[3.36222346 3.4514149 ]]
418
[[ 3.49518239 -3.54225801]]
[[3.43466862 3.54369966]]
414
[[ 4.16362836 -4.36705928]]
[[4.29080086 4.45114316]]
415
[[ 3.34598472 -3.34678155]]
[[3.30908993 3.44641658]]
419
[[ 3.52774411 -3.48729324]]
[[3.41441986 3.51066043]]
415
[[ 4.17516245 -4.36472834]]
[[4.28375637 4.46284021]]
416
[[ 3.34949181 -3.41947039]]
[[3.27592447 3.47183619]]
420
[[ 3.54452164 -3.47896428]]
[[3.44220267 3.55269019]]
416
[[ 4.14226575 -4.35784429]]
[[4.25800774 4.43967535]]
417
[[ 3.33594032 -3.33113022]]
[[3.31895899 3.47526283]]
417
[[ 4.18530735 -4.33403505]]
[[4.2593117 4.4231445]]
421
[[ 3.60062577 -3.51447773]]
[[3.46133279 3.61491383]]
418
[[ 3.36600227 -3.36524324]]
[[3.29292807 3.40326103]]
422
[[ 3.65097367 -3.50108622]]
418
[[3.48391517 3.64784664]]
[[ 4.14039615 -4.2859664 ]]
[[4.24652254 4.42905398]]
419
[[ 3.30076668 -3.34970964]]
[[3.35082544 3.35863746]]
423
[[ 3.59901728 -3.47693853]]
[[3.45965521 3.66015819]]
419
[[ 4.1466482

[[3.28253549 3.27435755]]
460
[[ 4.32740983 -4.32007997]]
[[4.38388322 4.53978703]]
464
[[ 3.4395919  -3.50924022]]
[[3.57861131 3.7444161 ]]
464
[[ 3.16055801 -3.19918822]]
[[3.3150516  3.27137119]]
461
[[ 4.32118521 -4.31617962]]
[[4.31802038 4.48590058]]
465
[[ 3.40789968 -3.53264908]]
[[3.60795586 3.65514822]]
465
[[ 3.16584891 -3.22902306]]
[[3.36225875 3.21912817]]
462
[[ 4.34156623 -4.34663149]]
[[4.27975887 4.48525289]]
466
[[ 3.38086834 -3.51661402]]
[[3.56223698 3.67751324]]
466
[[ 3.17103453 -3.24468354]]
[[3.34711461 3.21380065]]
463
[[ 4.33624729 -4.30206922]]
[[4.26968423 4.48500344]]
467
[[ 3.42562384 -3.51027577]]
[[3.58284637 3.63943377]]
464
[[ 4.28567446 -4.31859874]]
[[4.26730479 4.46834474]]
467
[[ 3.16202717 -3.20439476]]
[[3.30405546 3.2000738 ]]
468
[[ 3.42655843 -3.52650816]]
[[3.58496895 3.66222636]]
465
[[ 4.31633524 -4.33542946]]
[[4.24694408 4.48100513]]
468
[[ 3.20123492 -3.20074596]]
[[3.26307323 3.20271748]]
466
[[ 4.35921602 -4.31048384]]
[[4.20053881 4

9
[[ 3.22290763 -3.04117148]]
[[3.17427001 3.28382646]]
11
[[ 3.67732506 -3.691572  ]]
[[3.70980312 3.74125367]]
10
[[ 4.20991848 -4.34592859]]
[[4.25957359 4.28848484]]
10
[[ 3.20481042 -3.06613674]]
[[3.13513137 3.21172191]]
12
[[ 3.71082684 -3.64796083]]
[[3.7474995  3.81016978]]
11
[[ 3.21275913 -3.10735689]]
[[3.10953451 3.17645048]]
11
[[ 4.16075335 -4.33501488]]
[[4.28552558 4.3082542 ]]
13
[[ 3.72117036 -3.65175166]]
[[3.76536959 3.82279748]]
12
[[ 3.23607203 -3.11894963]]
[[3.18475742 3.16976548]]
12
[[ 4.16947529 -4.3409451 ]]
[[4.28133865 4.30720469]]
14
[[ 3.74671634 -3.66243764]]
13
[[ 3.27032281 -3.13584385]]
[[3.15859887 3.20632574]]
[[3.70286091 3.8271932 ]]
13
[[ 4.14825933 -4.30891951]]
[[4.26406564 4.31606583]]
14
[[ 3.24695902 -3.13835485]]
[[3.16281212 3.23454084]]
15
[[ 3.78125232 -3.66842979]]
[[3.70646545 3.82860572]]
14
[[ 4.10065579 -4.27184026]]
[[4.2547254  4.30608198]]
15
[[ 3.27194187 -3.17208592]]
[[3.18635007 3.20255447]]
15
[[ 4.12273194 -4.30144457]]
[

57
[[ 3.21841404 -3.26591904]]
[[3.28692391 3.15300943]]
59
[[ 4.46246147 -4.39984466]]
[[4.41912399 4.59896528]]
58
[[ 3.73376646 -3.78601154]]
[[3.77461326 3.95183248]]
58
[[ 3.22079641 -3.23386579]]
[[3.23642267 3.12413317]]
60
[[ 4.4515832  -4.36520922]]
[[4.41473186 4.61544959]]
59
[[ 3.77803185 -3.7967234 ]]
[[3.76500026 3.95936182]]
59
[[ 3.18679173 -3.26327121]]
[[3.24763566 3.15611115]]
61
[[ 4.49026123 -4.39897647]]
[[4.36671859 4.65233294]]
60
[[ 3.1935073  -3.28347203]]
60
[[3.2127441  3.16358303]]
[[ 3.80515295 -3.82660898]]
[[3.76477718 3.95525238]]
62
[[ 4.38825737 -4.36236355]]
[[4.40291843 4.63184774]]
61
[[ 3.81120427 -3.83687851]]
[[3.79069829 4.03086152]]
61
[[ 3.16880629 -3.25073287]]
[[3.22247102 3.19975165]]
63
[[ 4.43322191 -4.38784394]]
[[4.40791678 4.65658846]]
62
[[ 3.76687665 -3.87591467]]
[[3.8064473  3.95796145]]
62
[[ 3.17194947 -3.21022215]]
[[3.23002057 3.1447908 ]]
64
[[ 4.40954486 -4.35553076]]
[[4.3702405  4.66729532]]
63
[[ 3.74201781 -3.84329665]]


106
[[ 3.28713886 -3.24093061]]
[[3.41148036 3.48696776]]
106
[[ 4.58776982 -4.60942469]]
[[4.51960486 4.62700546]]
107
[[ 3.27973051 -3.27060781]]
[[3.44874377 3.56047601]]
106
[[ 3.82578371 -3.76769293]]
[[3.82144676 3.92598386]]
107
[[ 4.53590098 -4.58947675]]
[[4.51063493 4.64584569]]
108
[[ 3.23283477 -3.30354674]]
[[3.4360357  3.54962065]]
107
[[ 3.81566718 -3.79652538]]
[[3.80885568 3.93198598]]
108
[[ 4.52717152 -4.60139834]]
[[4.50638904 4.61809696]]
109
[[ 3.2262312  -3.36724222]]
[[3.43601268 3.58980825]]
108
[[ 3.83102608 -3.77866245]]
[[3.81804196 3.91837044]]
109
[[ 4.54520933 -4.61922898]]
[[4.49413305 4.59712001]]
110
[[ 3.24136458 -3.4342503 ]]
[[3.41154716 3.60054912]]
109
[[ 3.89850109 -3.79252066]]
[[3.79407052 3.93704362]]
110
[[ 4.53898586 -4.61638027]]
[[4.50550274 4.68513544]]
111
[[ 3.27169706 -3.43946709]]
[[3.38101815 3.54022932]]
110
[[ 3.84659782 -3.81303203]]
[[3.82573505 3.9445396 ]]
111
[[ 4.56714702 -4.56637063]]
[[4.48834991 4.6984096 ]]
112
[[ 3.23681

[[3.32573374 3.43839038]]
152
[[ 3.90299997 -4.05821877]]
[[3.99239908 4.12032012]]
154
[[ 4.33237045 -4.48275311]]
[[4.27098897 4.49248394]]
154
[[ 3.30276411 -3.33110745]]
[[3.36325441 3.4716469 ]]
153
[[ 3.88014409 -4.03957492]]
[[3.95709361 4.07168566]]
155
155
[[ 3.27901385 -3.35586453]]
[[3.35376616 3.45920519]]
[[ 4.29059969 -4.41786582]]
[[4.32025012 4.52121762]]
154
[[ 3.86432248 -4.01918632]]
[[3.95196442 4.06411243]]
156
[[ 3.32769365 -3.32243186]]
[[3.31079801 3.4474361 ]]
156
[[ 4.33242679 -4.42062045]]
[[4.25021097 4.47992596]]
157
[[ 3.32165515 -3.26407713]]
[[3.3517653  3.44923613]]
155
[[ 3.83327928 -4.02551493]]
[[3.93998437 4.05789294]]
157
[[ 4.30733639 -4.44355235]]
[[4.24336687 4.43940715]]
156
[[ 3.84952509 -4.02115429]]
[[3.94464034 4.12124844]]
158
[[ 3.31399072 -3.22916924]]
[[3.37306413 3.39892963]]
158
[[ 4.30709171 -4.45623159]]
[[4.27371178 4.420946  ]]
157
[[ 3.86852457 -4.02754933]]
[[3.89947008 4.14727121]]
159
[[ 3.30656242 -3.22438561]]
[[3.29277927 3

201
[[ 4.14622387 -4.25832103]]
[[4.02524867 4.35380763]]
199
[[ 4.13742146 -4.11920056]]
[[4.07370801 4.19241342]]
201
[[ 3.25642903 -3.1095246 ]]
[[3.28523118 3.27929468]]
200
[[ 4.19550038 -4.09944495]]
[[4.08095496 4.22932623]]
202
[[ 4.16245406 -4.21804027]]
[[4.02518211 4.32710824]]
202
[[ 3.27531207 -3.08537521]]
[[3.35467356 3.28266897]]
201
[[ 4.17281368 -4.04651329]]
[[4.04851655 4.19876179]]
203
[[ 4.17882264 -4.21534868]]
[[4.02762242 4.26903328]]
203
[[ 3.20765982 -3.08863981]]
[[3.34962604 3.25242846]]
202
[[ 4.14657299 -4.02767847]]
[[4.06828889 4.1849357 ]]
204
[[ 4.1398001 -4.2293842]]
[[4.07003122 4.25008566]]
204
[[ 3.20833095 -3.0701378 ]]
[[3.33667666 3.22108064]]
203
[[ 4.15617127 -4.07828391]]
[[4.12543223 4.19741574]]
205
[[ 4.15510682 -4.22944052]]
[[4.06590198 4.27218487]]
204
[[ 4.15184967 -4.03132298]]
[[4.10352997 4.19288819]]
205
[[ 3.19653733 -3.04786872]]
206
[[ 4.13301882 -4.24130329]]
[[4.11075461 4.23058576]]
[[3.33724054 3.20491492]]
205
[[ 4.1706515

[[4.20364019 4.05080146]]
248
[[ 4.10955299 -4.11747048]]
[[4.12706711 4.08296852]]
248
[[ 3.18495806 -3.21281987]]
[[3.15517163 3.47059145]]
247
[[ 3.88177666 -4.00565831]]
[[4.16757572 4.01494921]]
249
[[ 4.06408026 -4.05473705]]
[[4.09970891 4.08276835]]
249
[[ 3.21274085 -3.16787228]]
[[3.15818274 3.4549602 ]]
248
[[ 3.89212364 -3.96112008]]
[[4.12798464 3.9900833 ]]
250
[[ 4.0128986  -4.06310912]]
[[4.07601554 4.06028018]]
250
[[ 3.22733106 -3.16148545]]
[[3.11747855 3.4552797 ]]
249
[[ 3.91037845 -3.96579714]]
[[4.12122293 3.97317891]]
251
[[ 3.9903486  -4.03967996]]
[[4.11294211 4.01048696]]
251
250
[[ 3.22641511 -3.19781958]]
[[ 3.92206683 -3.92021304]]
[[3.15344963 3.47174651]]
[[4.12770024 3.97600266]]
252
[[ 3.95556144 -3.95308283]]
[[4.1287804  3.97703389]]
251
[[ 3.95748849 -3.93186166]]
[[4.06498042 3.96773786]]
252
[[ 3.24324771 -3.22957341]]
[[3.16039153 3.44858317]]
252
253
[[ 3.98427208 -4.00103914]]
[[4.1626896  4.02346146]]
[[ 3.93457155 -3.96661528]]
[[4.09228626 4

295
[[ 4.03361414 -3.90330633]]
[[3.77309938 3.97428876]]
293
[[ 3.56305922 -3.7498327 ]]
[[3.66536834 3.92765163]]
296
[[ 3.21561212 -3.2859693 ]]
[[3.16460492 3.41557152]]
294
[[ 3.5482359  -3.79181783]]
[[3.73206114 3.90232605]]
296
[[ 3.99549196 -3.95213757]]
[[3.73778839 3.97296778]]
297
[[ 3.2022807  -3.27832291]]
[[3.15819222 3.38357218]]
295
[[ 3.58089075 -3.79408243]]
[[3.69395244 3.90754572]]
298
[[ 3.22501701 -3.22667667]]
[[3.206645   3.37105634]]
297
[[ 4.01487806 -3.98164203]]
[[3.79980755 3.97399851]]
296
[[ 3.58395082 -3.80784331]]
[[3.71579547 3.89277838]]
299
[[ 3.25271992 -3.22802481]]
[[3.21726853 3.38065993]]
298
[[ 4.01427161 -3.95656328]]
[[3.79082372 3.94705235]]
297
[[ 3.62449746 -3.77584333]]
[[3.6778753  3.88440192]]
300
[[ 3.27014636 -3.25678994]]
[[3.20209903 3.3157709 ]]
299
[[ 4.03871476 -3.93179845]]
[[3.74047704 3.89420258]]
298
[[ 3.62760962 -3.84734691]]
[[3.65678487 3.86564253]]
301
[[ 3.25139023 -3.21357677]]
[[3.23506507 3.34605998]]
300
[[ 4.06319

[[3.95866109 3.93668001]]
344
[[ 3.13483643 -3.1234901 ]]
[[3.0788596  3.26726125]]
342
[[ 4.10151404 -3.85594672]]
[[3.96204991 3.94598915]]
340
[[ 3.66582174 -3.76385903]]
[[3.79432295 3.9658199 ]]
345
[[ 3.06956318 -3.08544029]]
[[3.05769752 3.23997907]]
343
[[ 4.09971798 -3.85040288]]
[[3.94487172 4.01511395]]
341
[[ 3.68909632 -3.73235101]]
[[3.77396803 3.94331388]]
346
[[ 3.05755627 -3.11293027]]
[[3.03333085 3.26201119]]
344
[[ 4.106903   -3.88852316]]
[[3.9122728  3.99807971]]
342
[[ 3.6731944  -3.71503003]]
[[3.76589593 3.9722472 ]]
347
345
[[ 4.10997212 -3.92677732]]
[[ 2.99299937 -3.10641358]]
[[3.05736573 3.22240553]]
[[3.90294156 3.98166261]]
346
[[ 4.11052835 -3.94495454]]
[[3.83388364 4.0264433 ]]
343
[[ 3.67740032 -3.7823027 ]]
[[3.78512933 3.9517735 ]]
348
[[ 3.0001873  -3.11107189]]
[[3.00541453 3.23968066]]
347
[[ 4.10136334 -3.94653048]]
[[3.88611195 4.09940128]]
344
[[ 3.704585   -3.77681527]]
[[3.80357748 3.95549907]]
349
[[ 2.99385927 -3.08743892]]
[[3.03812572 3

390
[[ 2.95211162 -3.05933653]]
[[3.09421953 3.15066595]]
387
[[ 3.71593424 -3.63512813]]
[[3.73003121 3.70526213]]
390
[[ 3.76558981 -3.78544204]]
[[3.8503708  3.91904892]]
391
[[ 2.97872633 -3.03211408]]
[[3.05654982 3.17532103]]
388
[[ 3.76868371 -3.67987807]]
[[3.76852448 3.72445236]]
391
[[ 3.76501941 -3.8078295 ]]
[[3.88760953 3.92916257]]
392
[[ 2.98474149 -2.99794082]]
[[3.00074832 3.21482203]]
389
[[ 3.76534661 -3.70313526]]
[[3.75426025 3.72320943]]
392
393
[[ 2.96399014 -3.03783611]]
[[3.03582384 3.17882064]]
[[ 3.75068617 -3.80707467]]
[[3.90511016 3.87193358]]
394
[[ 2.95014706 -3.05545888]]
[[2.97134089 3.17499392]]
390
[[ 3.79615263 -3.6827399 ]]
[[3.74402476 3.78608671]]
393
[[ 3.828818   -3.82754925]]
[[3.91480658 3.88596904]]
395
[[ 2.98486334 -3.10857775]]
[[2.96221432 3.16709017]]
391
[[ 3.77293663 -3.61553085]]
[[3.76200783 3.79087033]]
394
[[ 3.91473548 -3.81610701]]
[[3.86427635 3.93401479]]
392
[[ 3.82081868 -3.64475867]]
[[3.74992987 3.78502696]]
396
[[ 2.96811

[[3.74430448 3.92658564]]
436
[[ 3.78935497 -4.10507153]]
438
[[3.95846144 3.99081727]]
[[ 3.13024455 -2.94647205]]
[[3.08694654 3.09032516]]
435
[[ 3.81636578 -3.75543366]]
[[3.72817719 3.89841317]]
439
[[ 3.08074149 -3.00034567]]
[[3.04396292 3.06058344]]
437
[[ 3.84041538 -4.03866107]]
[[3.99315189 4.01488754]]
436
[[ 3.82667388 -3.82069526]]
[[3.76574319 3.83472303]]
440
[[ 3.07647509 -2.97005582]]
[[2.99549301 3.00184255]]
438
[[ 3.86632976 -4.03709463]]
[[3.95327613 4.04430103]]
437
[[ 3.81355091 -3.85134577]]
[[3.81327454 3.83853675]]
441
[[ 3.0428341  -2.93138494]]
[[3.00351043 3.02106715]]
439
[[ 3.89166315 -4.04796644]]
[[3.91911851 4.04300915]]
438
442
[[ 3.78740777 -3.81289664]]
[[ 2.9733625  -2.94786412]]
[[3.80929127 3.84647507]]
[[3.01043114 3.00509377]]
440
[[ 3.92754672 -4.06475588]]
[[3.94876035 4.03915796]]
443
[[ 2.998877   -2.95770893]]
[[2.9672018  3.00531222]]
439
[[ 3.74533152 -3.71461243]]
[[3.83983082 3.83259054]]
441
[[ 3.92300136 -4.04253351]]
[[3.94259719 4

480
[[ 3.75464901 -3.56627788]]
[[3.83624107 3.80741186]]
483
[[ 3.82211511 -3.91940492]]
[[3.80774827 4.16244999]]
481
[[ 3.76052045 -3.5844148 ]]
[[3.88136634 3.80168234]]
487
[[ 2.95815164 -2.99402431]]
[[2.99308178 3.10760516]]
484
[[ 3.83436118 -3.92273351]]
[[3.79182267 4.14600901]]
482
[[ 3.71301609 -3.59046621]]
[[3.86565687 3.81501804]]
485
[[ 3.84003072 -3.97206737]]
[[3.77544409 4.14598261]]
488
[[ 2.99367133 -3.00566611]]
[[3.03124383 3.14242503]]
486
[[ 3.83303857 -3.96191806]]
[[3.78701968 4.16210107]]
489
[[ 3.02271664 -3.00239519]]
[[3.03135435 3.07275826]]
483
[[ 3.71129041 -3.59288864]]
[[3.88444346 3.81962475]]
487
[[ 3.81418755 -3.91813713]]
[[3.78508187 4.12603714]]
484
[[ 3.6934155  -3.65036892]]
[[3.85341034 3.82746795]]
490
[[ 3.0565484  -2.96041115]]
[[2.98859034 3.06285505]]
488
[[ 3.84980831 -3.87060531]]
[[3.81931509 4.09125587]]
485
[[ 3.71031831 -3.63240816]]
[[3.89345493 3.840684  ]]
491
[[ 2.98431755 -2.98024221]]
[[2.97987061 3.03796605]]
486
[[ 3.76583

31
[[ 3.91092572 -3.8943218 ]]
[[3.7320379  3.82139058]]
31
[[ 3.14210337 -3.10552181]]
[[3.23724852 3.16922363]]
32
[[ 3.95488273 -3.85929054]]
[[4.02851024 4.09442241]]
32
[[ 3.88255608 -3.8851284 ]]
[[3.74594073 3.87333258]]
33
[[ 3.93873413 -3.87563492]]
[[4.01513722 4.10515558]]
32
[[ 3.17669232 -3.12619208]]
[[3.24591273 3.11268662]]
33
[[ 3.86843227 -3.88942322]]
[[3.79387722 3.86796297]]
34
[[ 3.92901974 -3.91484035]]
[[4.09776392 4.11636737]]
33
[[ 3.19660067 -3.13703035]]
[[3.23007765 3.13767   ]]
34
[[ 3.9019383  -3.86990979]]
[[3.80241043 3.87962493]]
35
[[ 3.86742802 -3.9529009 ]]
[[4.10565413 4.1286596 ]]
35
[[ 3.84965789 -3.89270087]]
[[3.76392744 3.88824532]]
34
[[ 3.19189877 -3.12497787]]
[[3.26416835 3.14915866]]
36
[[ 3.8749456  -3.98035022]]
[[4.09530436 4.14015927]]
36
[[ 3.82190693 -3.90195462]]
[[3.77800261 3.95876472]]
37
[[ 3.87314341 -4.03193482]]
[[4.089015   4.09975961]]
35
[[ 3.22002829 -3.15391594]]
[[3.25531701 3.15365863]]
37
[[ 3.82980947 -3.9227991 ]]


[[ 3.73119469 -3.77569958]]
[[3.7300166  3.80137792]]
82
[[ 3.88893034 -3.87387988]]
[[4.04765407 3.99458566]]
79
[[ 3.25829791 -3.2621793 ]]
[[3.1720547  3.25489262]]
83
[[ 3.94009543 -3.86497521]]
[[4.02606862 3.98806432]]
78
[[ 3.77296646 -3.83414994]]
[[3.77933475 3.8176446 ]]
80
[[ 3.29142779 -3.24871323]]
[[3.20569715 3.29321242]]
84
[[ 3.9368742  -3.89479577]]
[[3.99315808 4.00428223]]
79
[[ 3.80323196 -3.84092801]]
[[3.76949875 3.77881736]]
81
[[ 3.35773735 -3.2645439 ]]
[[3.2332511  3.31591763]]
85
[[ 3.88165346 -3.9356133 ]]
[[4.01069319 3.99107218]]
80
[[ 3.81353622 -3.79985178]]
[[3.75764845 3.78547617]]
82
[[ 3.34618078 -3.32727009]]
[[3.23060424 3.34985879]]
86
[[ 3.89252546 -3.9157265 ]]
[[3.98070985 3.97595574]]
81
[[ 3.89965056 -3.78333739]]
[[3.77655536 3.81511913]]
83
[[ 3.32199134 -3.25881525]]
[[3.2082109  3.38115837]]
82
[[ 3.88870024 -3.74988303]]
[[3.7191149  3.76947989]]
87
[[ 3.85655452 -3.90030224]]
[[3.9431313  3.99348105]]
84
[[ 3.30353455 -3.23120718]]
[[3

[[3.19703821 3.16257804]]
129
[[ 3.90426004 -3.86252522]]
[[3.85428233 3.87245874]]
125
[[ 3.87717003 -3.79025404]]
[[3.75827473 3.77936034]]
127
[[ 3.25065834 -3.18635622]]
[[3.19602561 3.18715689]]
130
[[ 3.92069751 -3.90478552]]
[[3.84420795 3.84822989]]
126
[[ 3.85877786 -3.82308602]]
[[3.75111696 3.75087038]]
128
[[ 3.29654257 -3.20823647]]
[[3.21360549 3.17651512]]
131
[[ 3.87353664 -3.92662674]]
[[3.8318576  3.90110428]]
129
[[ 3.2994352  -3.22493447]]
[[3.2076005  3.22288027]]
127
[[ 3.8357009 -3.7901756]]
[[3.69804757 3.75494258]]
132
[[ 3.86017721 -3.88475002]]
[[3.83877889 3.92896449]]
130
[[ 3.25471797 -3.25179245]]
[[3.20302238 3.20932725]]
128
[[ 3.82711414 -3.77705202]]
[[3.72470861 3.80288333]]
133
[[ 3.86918578 -3.89812276]]
131
[[ 3.25404546 -3.22935819]]
[[3.91489668 3.96932094]]
[[3.26548056 3.18137885]]
129
[[ 3.82429796 -3.7881246 ]]
[[3.6950113  3.80761717]]
134
[[ 3.86814771 -3.86079553]]
[[3.91619654 3.9574952 ]]
132
[[ 3.29867786 -3.21716237]]
[[3.2501685  3.2

177
[[ 3.83925197 -3.92480402]]
[[3.84214243 4.13967017]]
169
[[ 3.89026974 -3.79917197]]
[[3.82618057 3.87936184]]
176
[[ 3.2913194  -3.19940899]]
[[3.188848   3.25129965]]
178
[[ 3.84391132 -3.89173157]]
[[3.79973581 4.13497107]]
170
[[ 3.8748916  -3.77626489]]
[[3.78291659 3.88706355]]
179
[[ 3.83952315 -3.93687516]]
[[3.75768933 4.13246686]]
177
[[ 3.22979476 -3.29885048]]
[[3.15196991 3.24946237]]
171
[[ 3.90288362 -3.79502782]]
[[3.80808106 3.89643268]]
180
[[ 3.82819782 -3.87600964]]
[[3.72195754 4.17734721]]
178
[[ 3.21288532 -3.25449388]]
[[3.18225215 3.25996118]]
172
[[ 3.90975606 -3.87770856]]
[[3.78891402 3.94575528]]
181
[[ 3.81967755 -3.87748092]]
[[3.68060477 4.17561638]]
179
[[ 3.21775021 -3.23337396]]
[[3.16963688 3.21598507]]
173
[[ 3.93618349 -3.88385802]]
[[3.76422971 3.99522221]]
182
[[ 3.86933017 -3.8406842 ]]
[[3.71287564 4.09891724]]
180
[[ 3.19432437 -3.22714813]]
[[3.17029797 3.21619192]]
174
[[ 3.91657735 -3.91389433]]
[[3.80703352 3.95654573]]
183
[[ 3.86722

[[3.89517331 4.00505243]]
216
[[ 3.97766018 -4.01593069]]
[[3.98185873 4.09258993]]
224
[[ 3.14632404 -3.11863653]]
[[3.0853139  3.27175186]]
217
[[ 4.00692105 -4.00256563]]
[[3.95353958 4.05241599]]
224
[[ 3.99228287 -4.01079168]]
[[3.90020016 4.05642628]]
225
[[ 3.24555683 -3.12709157]]
[[3.03276166 3.2352288 ]]
218
[[ 4.00215241 -3.98421662]]
[[3.96547893 4.08069952]]
225
[[ 4.00108491 -4.02158807]]
[[3.90222214 4.04898274]]
226
[[ 3.26336723 -3.14472321]]
[[3.00045862 3.24285678]]
219
[[ 4.00058009 -3.97686608]]
[[3.94075124 4.0708597 ]]
226
[[ 3.99672929 -4.01335236]]
[[3.95718884 4.06608675]]
227
[[ 3.26724218 -3.12791576]]
[[2.99557904 3.22720488]]
220
[[ 4.01424368 -3.98506156]]
[[3.93507294 4.05980822]]
227
[[ 3.96168656 -4.02060197]]
[[3.95985905 4.11213252]]
228
221
[[ 3.29525183 -3.12987003]]
[[3.03068333 3.21336331]]
[[ 3.99086389 -4.00713356]]
[[3.95939292 4.01119338]]
228
[[ 4.01411344 -4.04130552]]
[[3.98207515 4.10637449]]
222
[[ 4.03989226 -4.04203728]]
[[3.96205304 4

270
264
[[ 3.96959081 -4.03382748]]
[[3.90974642 3.99997121]]
[[ 3.98168373 -3.92218554]]
[[3.93838087 4.13019187]]
271
[[ 3.37510744 -3.26197897]]
[[3.20404851 3.39121316]]
265
[[ 3.96667633 -3.91364259]]
[[3.96052183 4.1474257 ]]
271
[[ 4.02485383 -3.98423563]]
[[3.90600213 3.95372774]]
272
[[ 3.38801336 -3.25837391]]
[[3.2053974 3.3544311]]
266
[[ 4.04811378 -3.84549242]]
[[3.99267256 4.16500628]]
272
[[ 3.98889008 -4.00162813]]
[[3.90022663 4.00919237]]
273
[[ 3.36480266 -3.28331714]]
[[3.21120959 3.34176719]]
267
[[ 4.05298954 -3.87485138]]
[[3.9610537  4.10885232]]
273
[[ 4.01123215 -4.01219977]]
[[3.85340241 4.02489023]]
274
[[ 3.32167615 -3.23324557]]
[[3.2763624  3.33253447]]
268
[[ 4.03620072 -3.89823527]]
[[3.99597231 4.10335867]]
274
[[ 3.99733067 -4.01763162]]
[[3.78345559 4.07122229]]
275
[[ 3.3220408  -3.28077997]]
[[3.36418425 3.37201738]]
269
[[ 4.03583758 -3.89043505]]
[[4.03230245 4.13051756]]
275
[[ 4.02503967 -3.98404099]]
[[3.82066564 4.11952257]]
276
[[ 3.3278754

## After Burn-in: check ESS to stop

In [ ]:
#########################
# after stopping
# put results together
all_parameters = pd.DataFrame()
for i in range(n_chain):
    all_parameters = pd.concat([all_parameters, after_paras[i]])
df_alpy = all_parameters.iloc[:,0:L]
df_betay = all_parameters.iloc[:,L:(2*L)]
df_sigu = all_parameters.iloc[:,2*L]
df_sigv = all_parameters.iloc[:,2*L+1]

df_loglike = pd.DataFrame()
df_times = pd.DataFrame()
for i in range(n_chain):
    df_loglike = pd.concat([df_loglike, after_loglikes[i]])
    df_times = pd.concat([df_times, after_times[i]])
df_snr = pd.DataFrame([snr])


'''
#res = gibbs(N,R,Y,W,X,Z,U,V,alpha_y,beta_y,sigma_u2,sigma_v2,alp_u,beta_u,alp_v,beta_v,sig_y2)


# wrap up results
conv_itrs = int(res[8])

df_sigu = pd.DataFrame(res[0])
df_sigv = pd.DataFrame(res[1])
mt_alpy = np.matrix(np.zeros(shape=(conv_itrs+1,J)))
mt_betay = np.matrix(np.zeros(shape=(conv_itrs+1,J)))
# append truth
mt_alpy[0,] = alpha0.reshape(-1)
mt_betay[0,] = beta0.reshape(-1)

for nn in range(conv_itrs):
    mt_alpy[nn+1,] = res[2][nn]
    mt_betay[nn+1,] = res[3][nn]
df_alpy = pd.DataFrame(mt_alpy)
df_betay = pd.DataFrame(mt_betay)
df_times = pd.DataFrame(res[7])
'''



In [ ]:
# MSE of posterior mean
sigu_err = (df_sigu - 1).mean()[0] #np.sqrt(np.mean(np.power(df_sigu-1,2)))
sigv_err = (df_sigv - 1).mean()[0]
alpy_err = np.sqrt(np.power(df_alpy - alpha0.reshape(-1).mean(),2).mean())
betay_err = np.sqrt(np.power(df_betay - beta0.reshape(-1).mean(),2).mean())
df_res = pd.DataFrame([coef_scale,n,m,L,sigu_err,sigv_err,alpy_err,betay_err])